### ISSUE TITLE
Add 2.5m 4 and 6 way connectors.

### ISSUE THREAD

**Issue by boiler1** [UmbraSpaceIndustries/MKS#1001]
With the removal of the OKS parts there is a void with 2.5m connectors.  Previously we had OKS 4-way connector and OKS 6-way connector parts.  Currently there are no parts that fill that roll.

**Comment by boiler1** [comment]
It would fill this void if the MKS Tundra 2.5m Hub (Short) could have 2.5m connections added to the sides?

**Comment by theRagingIrishman** [comment]
same as https://github.com/UmbraSpaceIndustries/MKS/issues/1044
