### ISSUE TITLE
Allow incremental supply of MaterialKits for deploying modules

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#1004]
Most of the inflatables require a fairly large chunk of MaterialKits all at once to deploy. Of course that's fine in principle, but these deployments are usually the only reason to have large storage of MaterialKits, so it'd be nice if they could be deployed incrementally.

Whenever a bunch of MaterialKits have been produced, an engineer should be able to use these for partially completing the inflation process, using the other required resources for the same percentage. (This would mean there would also not need to be insane ElectricCharge storage just for this. Basically make it work like a regular resource converter and make the progress by the lowest resource availability.)

If there's no state to track the deployment progress, it would probably be okay to track it from the part mass?

The module state and animation could remain undeployed until all requirements are met.

(Scrapping the containers after deploying is such a waste since only half the mass is recycled.)

**Comment by dboi88** [comment]
I'd like to tag on a request to be able to use material kits in planetary storage when the vessel has both access and at least some storage for material kits present.

**Comment by jd284** [comment]
Fixed in 0.52.1 (not the planetary storage access, but with incremental support that's no longer needed that badly).
