### ISSUE TITLE
Remove "vesselType = Base" from most parts (except Duna and Ranger_AnchorHub)

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#1016]
Tundra and Ranger parts should be neutral to vessel type. Especially Tundra shouldn't be set to "Base" since they're also intended for orbital stations and it's really annoying if my stations keep reverting to "Base" and I can't find them after filtering by type until I remember this.

Even agriculture parts and such should remain neutral with no vesselType since they can be useful on orbital stations with attached asteroids for mining.

**Comment by voicey99** [comment]
Done as PR #1263.
