### ISSUE TITLE
Missing module error in the logs

### ISSUE THREAD

**Issue by ihsoft** [UmbraSpaceIndustries/MKS#1029]
```
161123T193814.328 [ERROR] [Part.AddModule] Cannot find a PartModule of typename 'ExWorkshop'
```

Installed USI mods:
* USI Core
* USI Kolonization Systems (MKS/OKS)
* USI Life Support
* USI Tools

There are a lot of such records on game load (more than 20).

**Comment by Kerbas-ad-astra** [comment]
The ExWorkshop module is from Extraplanetary Launchpads. It might arguably be better practice to take those modules out of the part configs and put them in a NEEDS[Launchpad]

**Comment by theRagingIrishman** [comment]
I just submitted PR #1190 which fixes this.
