### ISSUE TITLE
Orbital Shipyard Open Animation Loops continuously 

### ISSUE THREAD

**Issue by EarthQuakeMole** [UmbraSpaceIndustries/MKS#1033]
Getting an issue where the "Orbital Shipyard Open Animation Loops continuously" confirmed by a couple
other people on the form. 
-Nothing special to when it happens 
-Close animation works fine
 
I have uninstalled all my mods except USI kolonization systems though CKAN. This gave me 
-USI Core
-USI Kolonization systems
-USI Tools
-Module Manager 2.7.4
-Firespitter core
-Community Resource Pack 
-Konstruction 

Need anything else, please let me know, (I'm relatively new to to reporting)

**Comment by Forgilageord** [comment]
Uninstall everything and manually install, see if it still happens. Could be a CKAN issue.

**Comment by mcortez** [comment]
May be related, but I'm seeing the same behavior on the DERP Service ring while in the VAB

**Comment by micahculpepper** [comment]
I've got the same issue with the Orbital Shipyard. I'm not experiencing the issue with the DERP service ring.

I suspected CKAN shenanigans, so I uninstalled all of my USI Mods, deleted their folders, and re-installed from github downloads (deleted the module manager cache files, too). Still same issue.

**Comment by scorpion451** [comment]
Temporary workaround that works for me: toggle the switch a couple of times and it'll stay closed.

**Comment by draqsko** [comment]
Found the issue with this animation and the DERP service ring: Firespitter(core) 7.4.2. If I revert it back to version 7.4.1, the animations for both parts play properly in both the VAB and out in play. Fully tested on a clean KSP install with only MKS, and then the entire USI constellation, just copying the Firespitter folder from this repository: https://github.com/BobPalmer/USI_Constellation/releases/tag/2016.10.23.01, into the relevant folder in KSP works for fixing the animations. Going to reinstall my other 50 mods now and if you don't hear back from me then this worked as a fix and whatever changes made in FS need to be explored.

**Comment by jd284** [comment]
It's probably the changes to FSanimateGeneric.cs in the [2e5a97e](https://github.com/snjo/Firespitter/commit/2e5a97e7f05aaf58dce662f73ac2221aad7b6e4b) commit.
Not sure if that commit has bugs or if the new fields just need to be set properly.

**Comment by draqsko** [comment]
Just tested with Firespitter 7.5.0 and the parts animate normally now, this and the related issue with the DERP service ring can be closed.

**Comment by davidpridemore** [comment]
Not working with Firespitter 7.5.0 for me.
