### ISSUE TITLE
ElectricCharge taken into account in planetary logistic

### ISSUE THREAD

**Issue by Luskhen** [UmbraSpaceIndustries/MKS#1036]
Hello,
In my recent tests near KSC I've noticed that Electric Charge gets pushed into planetary storage.
I don't know if it's by design in 0.50 but I'll try to make a PR regarding this.

Please disregard this issue if it was intended.

**Comment by Luskhen** [comment]
#1037

**Comment by kaa253** [comment]
I doubt this is intended. My reactor is running full tilt and real hot busy pumping EC into planetary storage.

**Comment by jd284** [comment]
Workaround is to disable the warehouse on any warehouse parts with EC storage, such as the Karibou Multi-Hub. Maybe rather than hardcoding an exception for EC, the EC storage could be removed from warehouses?

**Comment by Luskhen** [comment]
That is a more elegant way of doing this ! 
I did not noticed at first but it was indeed a karibou part that was the source of EC being pushed. I'll take back the PR and see if I can make another one on the Karibou cfg (I was not fond of hardcoding this exception in the dll either). 
Thanks.
