### ISSUE TITLE
NullReferenceException on KolonyTools.ModuleLogisticsConsumer.FixedUpdate() in KSP 1.2.2

### ISSUE THREAD

**Issue by maehluml** [UmbraSpaceIndustries/MKS#1042]
Updated to KSP 1.2.2, and while I know it's not explicitly compatible, this exception spammed into my log file every ms makes the game completely unplayable.

> [EXC 10:56:35.334] NullReferenceException: Object reference not set to an instance of an object
	KolonyTools.ModuleLogisticsConsumer.FixedUpdate ()
[EXC 10:56:35.335] NullReferenceException: Object reference not set to an instance of an object
	KolonyTools.ModuleLogisticsConsumer.FixedUpdate ()
[EXC 10:56:35.336] NullReferenceException: Object reference not set to an instance of an object
	KolonyTools.ModuleLogisticsConsumer.FixedUpdate ()

Hopefully this is something that is fixed in the next release, but added it as an issue anyway.

**Comment by theRagingIrishman** [comment]
assuming this was fixed 😶
