### ISSUE TITLE
Tundra Adapters and Konstruction cradles too massive

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#1089]
The 3.75m adapter has basically the same function and shape as the stock Kerbodyne ADTP-2-3 (which has a mass of 0.2 t), however the Tundra adapter is less than a quarter in height. So the 3.75m adapter should have a mass of about 0.1 t instead of 0.75t, and the 2.5m adapter closer to 0.05t instead of 0.5t (or maybe 0.08t like the Rockomax adapter which is nearly identical in shape).

Similarly the 2.5m cradle contains basically the equivalent of 4 LT-2 landing legs and the bottom half of the ADTP-2-3 so its mass should be closer to 0.5t instead of 1t, and probably 1.25t for the 3.75m cradle.

**Comment by theRagingIrishman** [comment]
fixed
