### ISSUE TITLE
Sun receives Kolonization values

### ISSUE THREAD

**Issue by dgbinger** [UmbraSpaceIndustries/MKS#1098]
Since you can't mine in the solar SOI anyway (unless asteroid mining is affected, but that seems like correct behavior anyway) this was formerly more of a quirk than a bug. With the new 500% Kolonization=infinite hab rule, though, it's now possible (and not even especially difficult, compared to other bodies) to set up permanent solar colonies, which is a bit of a hack.

**Comment by Kerbas-ad-astra** [comment]
I think it seems fair enough -- put enough colonies in orbit around the Sun, and people get used to the idea of being at home in solar orbit.

**Comment by dgbinger** [comment]
Sure, as far as colonies go, it is. The trouble is, it messes with transit times. Since it's easy and quick to travel between Kerbin and solar orbit, and especially since pilots no longer need to care about hab time, you can put a pack of pilots in solar orbit with nothing but a tank of fertilizer and some agroponics modules. Rack your solar Kolonization values up to 500% (which, admittedly, is non-trivial but isn't crazy-hard either) and instead of needing a giant ark-ship to get to Jool (hab time ~8 years for a round trip, assuming your windows are relatively convenient), you need only one year of hab.

**Comment by toric55** [comment]
what about only having hab values for landed colones? that way even orbital colonies need to land somewhere every once in a while...

**Comment by voicey99** [comment]
Kerbol is now blacklisted from gaining Kolonisation values, so this issue has been fixed and can be closed.
