### ISSUE TITLE
MEU-100 Pulse Drill animation have grey squares

### ISSUE THREAD

**Issue by LouisCyfer** [UmbraSpaceIndustries/MKS#1101]
no need to explain much more (already did that in the thread [here](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-12x-temporary-mks-karbonite-support-thread/&do=findComment&comment=2917728) and [here](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-12x-temporary-mks-karbonite-support-thread/&do=findComment&comment=2918486))

.. basicy, the texture(s) of the drill animation might be missing

screen:
![mks_drills_issue](https://cloud.githubusercontent.com/assets/19025056/21868603/d684541e-d853-11e6-8679-0e3b0c64ff61.png)

savegame:
[persistent.sfs.txt](https://github.com/BobPalmer/MKS/files/700231/persistent.sfs.txt)

**Comment by voicey99** [comment]
This has now been fixed and this issue can be closed.
