### ISSUE TITLE
Efficiency parts should ignore specialty and kolonization bonus and always have 100% max load

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#1114]
See also the [forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-12x-temporary-mks-karbonite-support-thread/&do=findComment&comment=2922472).

Currently the effective load of an efficiency part is the square of the specialty/kolonization bonus, because the Tundra part applies the same factor again, e.g. for two stars 65%*65% = only 42% effective load.

So when set to efficiency part mode, the max load should ignore the specialty and kolonization bonus and always be a flat 100%.

**Comment by jd284** [comment]
In 0.50.13 the efficiency parts do ignore the specialty bonus but for some reason they're now running at over 200% load. None of my kolonization bonuses is over 150% so this is a number I can't explain.

**Comment by Gilph** [comment]
I have the same issue.  My [Crusher] efficiency part on one base and my [Greenhouse] efficiency part on another base close by both run at 356%. My Kolonization bonus is 150.8%. All resident kerbals are 3 star.
