### ISSUE TITLE
 "refuses to work - returned to duty" spam 

### ISSUE THREAD

**Issue by sh1pman** [UmbraSpaceIndustries/MKS#1124]
Every time I open the LS window in my Mun base I see these "refuses to work - returned to duty" messages constantly appearing. 
Everything is fine if I focus the vessel where all the Kerbals are. But if I focus something else and open the LS window, it starts spamming these notifications.
Check the Mun base in the save file below.
https://dl.dropboxusercontent.com/u/46597246/LSBug.sfs

**Comment by jd284** [comment]
This should probably be in the USI-LS tracker instead...

**Comment by theRagingIrishman** [comment]
usils issue
