### ISSUE TITLE
Make hiring list dynamic

### ISSUE THREAD

**Issue by DanStaal** [UmbraSpaceIndustries/MKS#1158]
The hiring list in the new addition to the hiring facility are hard-coded in; ideally it would get a list of possible Kerbal professions and automatically create the list.  Better than current but not ideal would be to have it controlled by a .cfg file.  (Which might allow more flexibility in regards to setting prices for specific professions/traits, etc.)

**Comment by theRagingIrishman** [comment]
duplicate issue
