### ISSUE TITLE
Nullrefs on PM

### ISSUE THREAD

**Issue by Gilph** [UmbraSpaceIndustries/MKS#1163]
Hi, this is in reference to #1152  Issue still exists

Made a new vessel and landed on Minmus, in same career save as above. Same issue. Also the same in USI only save. Save and log are here: [(https://1drv.ms/f/s!AigvIEvgjetqwnIsiTUUARa4Tork)]

Go to vessel Minmus PDU3. Eva the engineer and perform maintenance on the parts,  You will see the nullrefs in the log.  Thanks

**Comment by theRagingIrishman** [comment]
was declared fixed in https://github.com/BobPalmer/MKS/issues/1152
