### ISSUE TITLE
Extra Drill Buffs

### ISSUE THREAD

**Issue by voicey99** [UmbraSpaceIndustries/MKS#1179]
Drills in MKS add the Geology multiplier to their efficiency, and don't remove the 100% base level from that multiplier, resulting in much higher than expected efficiency multipliers.

**Comment by Gnurfos** [comment]
You make it sound as if there are 2 systems stacked. But as far as I know, Kolonization bonuses always work as a pair geology + one of the others (which can be geology again), and this is the same as for converters. (you either get geology squared, or geology*botany, etc ...). Do you have values examples, in case it's a bug ? Or do you think drills should benefit from a less powerful boost than converters ? Or that the whole bonuses system is too powerful overall ?

**Comment by voicey99** [comment]
This was brought up on the forums a while back, on page 72. I had a base on Minmus with 183% geology, but was getting 283% load-and RD had this to say:

"huh... that extra 100% is a bug, need to sort that   Should have been just 183% in your case"

**Comment by Gnurfos** [comment]
If I remember correctly, more precise calculations revealed that it was not an extra +100% but just the geology bonus squared.

**Comment by voicey99** [comment]
Considering none of the other variables has changed, it looks like the formula has changed around a bit since then, the drills are now running at 163% load. From the handy MKS Explainer plugin, the formula is now thermaleff*no. drill bits*specialist mult*geobonus sqrd.

Closing the issue as the bug has been fixed.
