### ISSUE TITLE
Permanent Tourist Bug is back

### ISSUE THREAD

**Issue by PolecatEZ** [UmbraSpaceIndustries/MKS#1185]
Steps to reproduce (not tested - based on what happened).

1) Accepted rescue mission of a pilot kerbal in low Minmus orbit.  Kerbal was flying in a Ranger Auxiliary Control module.

2) Intercepted into 2km physics range of the module with rescue ship.  Ship had accommodations for 60 days of supplies and hab time.

3) During the burn to get closer, got message that kerbal went "off duty" due to lack of EC.

4) Switching to RAC module with kerbal, noted the kerbal is now a tourist (was a pilot).

5) Was able to EVA with the kerbal (still noting tourist outside the pod) and get him into the rescue ship.  Hab time and supplies went to 30 days for both crew.  Rescue kerbal was still showing a red T for tourist.

6) Returned to Kerbin and landed.  Kerbal did not recover when entering 25km altitude on Kerbin.

7) Taking the Kerbal on a new mission on the runway, could still EVA, plant a flag, etc.  Was still noted as a tourist and had no profession skills.

**Comment by BobPalmer** [comment]
Will need a save file for this one.

**Comment by theRagingIrishman** [comment]
consolidating into https://github.com/UmbraSpaceIndustries/MKS/issues/1235
