### ISSUE TITLE
Drills missing Ore Harvesting - With solution

### ISSUE THREAD

**Issue by Leitk** [UmbraSpaceIndustries/MKS#1217]
The non-automated versions of the drills (Industrial Strip Miner, MEU 100, and MEU 500) are missing Ore.
I can update the config files and it seems to add it back in.

**Comment by Leitk** [comment]
[MKS Drills.zip.zip](https://github.com/BobPalmer/MKS/files/859927/MKS.Drills.zip.zip)

Here are the part files for the drills with Ore added, copied from the automatic parts, with the auto config part swapped for the manual part.

**Comment by theRagingIrishman** [comment]
I put these changes into https://github.com/UmbraSpaceIndustries/MKS/pull/1261 so if RoverDude confirms this is a bug, he can quickly fix it
