### ISSUE TITLE
Planetary Logistics: LFO & Ox

### ISSUE THREAD

**Issue by M3tal-Warrior** [UmbraSpaceIndustries/MKS#1228]
Planetary Logistics works for all other resources, but not for LFO and Ox. Is that intentional?

**Comment by sh1pman** [comment]
Works for me.

**Comment by M3tal-Warrior** [comment]
I landed a vessel with round tanks that work otherwise for mulch without problems. I pushed all LFO+Ox inside but they won't be pushed to planetary storage. I don't know about pulling, haven't tried that yet.

**Comment by BobPalmer** [comment]
Make sure planetary logistics is turned on, and that said vessel is attached to something that has logistics capabilities

**Comment by M3tal-Warrior** [comment]
I tried a couple of things now, but whatever I do it doesn't work:
[URL=http://www.imagebanana.com/view/botgq5sv/screenshot33.png][IMG]http://i.imagebanana.com/img/botgq5sv/thumb/screenshot33.png[/IMG][/URL]

**Comment by M3tal-Warrior** [comment]
Ok, that is awkward, it works now - I had to somehow restart the game once again. I'm sorry for bothering, thanks for the help!
