### ISSUE TITLE
Collision Errors with Karibou Parts

### ISSUE THREAD

**Issue by M3tal-Warrior** [UmbraSpaceIndustries/MKS#1244]
I tried to launch a Karibou vessel via Extraplanetary Launchpads, and it kept glitching through the ground. Tried again from SPH on the Runway, same problem - glitch through ground. Relevant messages (output.log snippet):
Unpacking Karibou Konst Hopper
 (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
Look rotation viewing vector is zero
(Filename:  Line: 82)
computeMassAndInertia: Provided mass or density has no valid value
(Filename: ..\..\PhysXExtensions\src\ExtRigidBodyExt.cpp Line: 130)
PxRigidBodyExt::setMassAndUpdateInertia: Mass and inertia computation failed, setting mass to 1 and inertia to (1,1,1)
(Filename: ..\..\PhysXExtensions\src\ExtRigidBodyExt.cpp Line: 345)
recalculating orbit for KER.RoverCab: Kerbin ( Update mode TRACK_Phys )
rPos: [-490934.570870996, -508.960254624486, 345063.607897282]   rVel: [-100.610506905025, 0, -143.142234944796] |174.96334908968|
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
recalculated orbit for KER.RoverCab: the Sun ( UT: 14334289.618238 )
rPos: [NaN, NaN, NaN]   rVel: [NaN, NaN, NaN] |NaN|
Delta: [NaN, NaN, NaN] / [NaN, NaN, NaN]
Look rotation viewing vector is zero
(Filename:  Line: 82)
Warning ! ActiveVessel is landed and heightFromTerrain are negative (-1)
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
Kerbin: Resetting
Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "KER.RoverCab/model/UmbraSpaceIndustries/Karibou/Assets/KER_RoverCab(Clone)/RoverCab_2/_HUB_002/PistonCap/UppderPiston/MiddlePiston/LowerPiston/Foot/FootCol_002"
 
After a view tests I think I figured the problem: The moment the VTOL Descent Engine gets (potentially) loaded with LF/Ox, the glitch happens. This is even true when taking the craft with a second one and transporting it somewhere else. It might have to do with Goodspeed FuelPump, since that's what I use for managing my resources automatically, but then it even happens without any LF/Ox on board, by just giving the engine a FuelPump setting lower than even one other container on the vessel.

**Comment by M3tal-Warrior** [comment]
Just a short report on KSP v1.3 - the issue persists, although it takes about 2-4 seconds to occur. Tell me if you need a ship file.

**Comment by BobPalmer** [comment]
Did you test this without any other mods?

**Comment by M3tal-Warrior** [comment]
Did that just now. Used CKAN to install only GPOSpeedFuelPump and MKS (with dependencies). 

Steps to reproduce:
0. Start new game, install required mods (see above).
1. Build a minimal Karibou Rover with Cockpit, VTOL Descent Engine and Wheeled Storage Bay in SPH
2. Proceed to Runway
3. Right click on VTOL Engine, select 'Balance' -> Kraken

Happens every time.

**Comment by BobPalmer** [comment]
Let's try that again... does it happen WITHOUT GPOSpeedFuelPump?

**Comment by M3tal-Warrior** [comment]
No, of course not, because the button is not there without GPOSpeedFuelPump. The whole point of the mod is to balance/manage fuel levels in the different components of the vessel (works with all other resources too, that's why it's very convenient with your whole mod ecosystem). 

I see you blaming GPOSpeedFuelPump, and indeed it looks like it's the culprit alltogether and there's no bug on your side. Fair stance - unless it doesn't happen with other engines that bring their own fuel. Like the stock LFB KR-1x2 "Twin-Boar" Liquid Fuel Engine. So I tested the same setup, and just switched engines. No Kraken. The Twin Boar has no problem with fuel balancing. (Nor do any of your other parts. It's just the VTOL).

So yes, I'm dead sure it's something within the VTOL, some weird corner case that looks fine on first, second and third glance, but sleeps and waits for the time to strike.

**Comment by BobPalmer** [comment]
Sorry, closing this as it is clearly a GPOSpeedFuelPump issue.  There is nothing magical about that VTOL engine, it is 100% stock with two transforms.

**Comment by M3tal-Warrior** [comment]
I'll file a bug against GPOSpeedFuelPump then.

Thanks for looking into it. Keep rocking! :+1:
