### ISSUE TITLE
inflatable LFO tank  mass is -12 wen using LqH2

### ISSUE THREAD

**Issue by danielboro** [UmbraSpaceIndustries/MKS#1260]
mod list
just copy ckan`s list :P

			"name": "ModuleManager"
			"name": "NearFuturePropulsion"
			"name": "USI-LS"
			"name": "Konstruction"
			"name": "BetterCrewAssignment"
			"name": "KerbalAtomics"
			"name": "B9PartSwitch"
			"name": "AllYAll"
			"name": "Graphotron"
			"name": "DockingPortAlignmentIndicator"
			"name": "Trajectories"
			"name": "AmpYearPowerManager"
			"name": "EVAStruts"
			"name": "GravityTurnContinued"
			"name": "HangarGrid"
			"name": "xScience"
			"name": "EVAParachutes"
			"name": "KSP-AVC"
			"name": "USITools"
			"name": "IONRCS"
			"name": "NearFutureElectrical-DecayingRTGs"
			"name": "TakeCommandContinued"
			"name": "JanitorsCloset"
			"name": "LithobrakeExplorationTechnologies"
			"name": "DeflatableHeatShield"
			"name": "MechJebForAll"
			"name": "TweakScale"
			"name": "AirlineKuisine"
			"name": "PortraitStats"
			"name": "ContractConfigurator"
			"name": "SolarSailNavigator"
			"name": "RCSBuildAid"
			"name": "Kopernicus"
			"name": "KRASH"
			"name": "FilterExtensionsDefaultConfig"
			"name": "ThrottleControlledAvionics"
			"name": "InterstellarFuelSwitch-Core"
			"name": "ContractConfigurator-CleverSats"
			"name": "UnmannedBeforeManned"
			"name": "DistantObject-default"
			"name": "SETI-Contracts"
			"name": "WaypointManager"
			"name": "MalemuteRover"
			"name": "KerbalAlarmClock"
			"name": "DMagicOrbitalScience"
			"name": "ScienceRelay"
			"name": "InterstellarFuelSwitch"
			"name": "Toolbar"
			"name": "CustomBarnKit"
			"name": "MiniSampleReturnCapsule"
			"name": "SmartStage"
			"name": "SCANsat"
			"name": "ContractConfigurator-Tourism"
			"name": "TextureReplacer"
			"name": "UniversalStorage"
			"name": "FirespitterCore"
			"name": "USI-ART"
			"name": "DMagicScienceAnimate"
			"name": "TransferWindowPlanner"
			"name": "CommunityTechTree"
			"name": "USI-EXP"
			"name": "ContractConfigurator-FieldResearch"
			"name": "CryoEngines"
			"name": "ContractConfigurator-RemoteTech"
			"name": "ConfigurableContainers-Core"
			"name": "SmartParts"
			"name": "Impact"
			"name": "CapCom"
			"name": "ProgressParser"
			"name": "ContractParser"
			"name": "CactEyeCommunity"
			"name": "FlightPlan"
			"name": "StageRecovery"
			"name": "LaserDist"
			"name": "BetterBurnTime"
			"name": "KerbnetController"
			"name": "AsteroidDay"
			"name": "ContractConfigurator-KerbalAcademy"
			"name": "ContractConfigurator-UnmannedContracts"
			"name": "FilterExtensions"
			"name": "SpacetuxSA"
			"name": "BonVoyage"
			"name": "StationScienceContinued"
			"name": "NearFutureProps"
			"name": "QuickSearch"
			"name": "KSPInterstellarExtended"
			"name": "AT-Utils"
			"name": "ContractConfigurator-RoverMissionsRedux"
			"name": "KAS"
			"name": "KerbalEngineerRedux"
			"name": "EditorExtensionsRedux"
			"name": "DatedQuickSaves"
			"name": "SensibleScreenshot"
			"name": "DistantObject"
			"name": "MagiCore"
			"name": "kOS"
			"name": "MechJeb2"
			"name": "USI-SRV"
			"name": "PersistentThrust"
			"name": "CorrectCoL"
			"name": "UKS"
			"name": "Strategia"
			"name": "NearFutureElectrical"
			"name": "WalkAbout"
			"name": "WhoAmI"
			"name": "SurfaceExperimentPack"
			"name": "NearFutureElectrical-Core"
			"name": "USI-SubPack"
			"name": "TarsierSpaceTechnologyWithGalaxies"
			"name": "KerbalAtomics-NFECompatibility"
			"name": "AdditionalProgressionContracts"
			"name": "ContractConfigurator-ContractPack-SCANsat"
			"name": "NearFutureConstruction"
			"name": "NearFutureSolar"
			"name": "DeployableEngines"
			"name": "CryoTanks"
			"name": "StationPartsExpansion"
			"name": "REPOSoftTech-Agencies"
			"name": "AutomatedScreenshots"
			"name": "Ceteras-Suit-Pack"
			"name": "RoverScienceRevisited"
			"name": "ModularFlightIntegrator"
			"name": "RemoteTech"
			"name": "NearFutureSpacecraft"
			"name": "OuterPlanetsMod"
			"name": "CommunityTerrainTexturePack"
			"name": "NearFutureSolar-Core"
			"name": "ContractConfigurator-KerbinSpaceStation"
			"name": "PlanetWiki-OPM"
			"name": "CommunityCategoryKit"
			"name": "ContractConfigurator-InterplanetaryMountaineer"
			"name": "CommunityResourcePack"
			"name": "ShipSectionsContinued"
			"name": "PartWizardContinued"
			"name": "ContractConfigurator-GrandTours"
			"name": "ExtensiveEngRptContinued"
			"name": "AtmosphereAutopilot"
			"name": "KIS"
			"name": "JX2Antenna"
			"name": "Workshop"
			"name": "USI-Core"
			"name": "GroundConstruction-Core"
			"name": "JoolBiomes"
			"name": "USIKolClassSuits"
			"name": "WernherCheckerContinued"
			"name": "TacFuelBalancer"
			"name": "KerboKatzSmallUtilities-PhysicalTimeRatioViewer"
			"name": "KerboKatzUtilities"
			"name": "EvaFuelCont"
			"name": "ExtendedInfoSciExp"
			"name": "SlingShotterReslung"
			"name": "FlexibleDocking"
			"name": "NavUtilities"
			"name": "KramaxAutopilotContinued"

**Comment by theRagingIrishman** [comment]
please delete your ModuleManager.ConfigCache, open KSP, and then post your KSP.log. This will let me see exactly what mod is changing the tank

**Comment by danielboro** [comment]
the log file

https://yadi.sk/d/vukDwMvF3HMHtx

**Comment by theRagingIrishman** [comment]
alright so the three mods that could be affecting this part are KSPI-E, CryoTanks, and IFS. Time for testing!

**Comment by theRagingIrishman** [comment]
fixed!
