### ISSUE TITLE
Ranger and Tundra ISM capacity

### ISSUE THREAD

**Issue by FrontLineFodder** [UmbraSpaceIndustries/MKS#1264]
I'll do a PR in the next day or so for the refining/assembly aligned FSfuelSwitch configs, not sure when you are planning an update next. on a related note, I've run some numbers on the two inflatable tanks using KIS volumes (hardcoded 1000 values temporarily removed)

MKS Ranger_ISM is detected by KIS as 119,424 units of Volume, and can fit 7,000 units of stuff (combined)
MKS Tundra_ISM is detected by KIS as  99,343 units of Volume, and can fit 7,000 units of stuff (combined)
MKS RoundFlat 2.5m tank is detected as 8,603 units of Volume, and can fit 4,500 units of stuff

8603 * 2 = 17,206 @ 9000 units of stuff (28% more storage than the ISM's)
Tundra volume 99,343 / 2.5m tank volume 17,206 = 5.7 times bigger
Ranger volume 119,424 / 2.5m tank volume 17,206 = 6.9 times bigger

Stock Large Holding Tank is detected as 775 units of Volume, and can fit 1,500 units of stuff(ore)
Tundra volume 99,343 / Large Holding Tank volume 775 = 128 times bigger

MKS C3_Tank_03 (3.75m) is detected as 90,484 units of Volume, and can fit 65,000 units of stuff(eg Mulch)
Tundra volume 99343 is comparable (weight is much less, but it's inflatable)

given this,
Suggest we bump the inflated Ranger_ISM tank to 49,000 units  (7x current size)
Suggest we bump the inflated Tundra_ISM tank to 42,000 units  (6x current size)

I can check if the adjusted numbers cause any issues with this #1031 for both the existing 11 configs and my proposed refining/assembly aligned configs

**Comment by theRagingIrishman** [comment]
What did you end up doing in the PR? Did you increase the volumes?

**Comment by FrontLineFodder** [comment]
Not yet, there was no discussion, so I did not know if I should

**Comment by FrontLineFodder** [comment]
The pr is just for the ratio specific configs

**Comment by theRagingIrishman** [comment]
OK just wanted to know if it ought to be closed. I'll talk to the other people and see what they think.

**Comment by theRagingIrishman** [comment]
1.25 white kontainer has volume of about 0.76 m3 and can hold 600 units leading to a unit/m ratio of  about 790. 2.5 white kontainer has a volume of about 6.1 m3, 4500 units, 733 ratio. 3.75->22m3, 15000 units, 679 ratio. 5->49m3, 37500 units, 763 ratio. The average ratio here was about 740 units/m3.

1.25 box kontainer is 2m by 1m with 4x.03m2 triangles cut out. This leads to a volume of  1.88m3 holding 2000 units with a ratio of 1065. 2.5 box is 4m by 2m with 4x.12m2 triangles cut out v=15.02m3 with 16000 units and a ratio of 1065. 3.75 box v=50.7m3 54000 units ratio of 1065. 5m 120.2m3 128000 units ratio of 1065.

Tundra is about 5.625m long and 2.1875m radius so (treating it like a perfect cylinder cause I'm tired) it has a volume of 84.56 so at 7000 units that's a ratio of 82! Ranger has floor radius of 2.5m, the cylyndrical part of it is 1.875m tall and the dome is 2m tall so it has a volume of 36.81m3+26.17m3=63.995m3 so a ratio of 111.

Looking at this I'd say bump them up even higher, I think the inflatables should be better than white cylinders but worse than the boxes so I'd increase the Ranger to somewhere between 49000 (7x) and 56000 (8) and the Tundra between 70000 (10x) and 77000 (11x) depending on what would work with the resource ratios. This would put their unit/volume ratio in the mid 800s.

Thoughts?

**Comment by FrontLineFodder** [comment]
No issues with the Tundra being bigger than the ranger, as that was how I understood RD intended it to be. 
I was getting the volume simply from KIS module, how did you get the numbers ?
i think the ranger x7 and tundra x10 would work

**Comment by theRagingIrishman** [comment]
I went through and measured them in game using parts with known sizes. KIS tries to get volume from collider and colliders are not always representative of the true shapes.

**Comment by FrontLineFodder** [comment]
ahh I was going to do that, except KIS seemed simpler :)

**Comment by theRagingIrishman** [comment]
Alright I'll change them to have x7 and x10 capacity. Is there anything special I need to do to make sure the numbers will work out fine?

**Comment by FrontLineFodder** [comment]
nope, just the multiplier, from 100 to 700/1000
that known bug wont be an issue

**Comment by FrontLineFodder** [comment]
I would like to find a way to prevent adding resources in the VAB/SPH so it can only be used post inflation.
Might look for a way to make something like the module switcher for resource tanks.

**Comment by FrontLineFodder** [comment]
do you know if it is possible to get a copy of the ranger inflatable model? & the font RD used for the test in the ranger series ?

**Comment by theRagingIrishman** [comment]
I'll ask him about it. I'm going to close this issue but feel free to keep commenting on it.
