### ISSUE TITLE
Tourist class from rescue contract?

### ISSUE THREAD

**Issue by Baladain** [UmbraSpaceIndustries/MKS#1265]
Performed a rescue contract and Kerbal seems to be of class: Tourist
Save is heavily modified, but only USI should affect kerbals directly.
Danny Kerman is at KSC, but still a tourist

(changed file extenstion to txt for github compatibility)
[persistent.txt](https://github.com/UmbraSpaceIndustries/MKS/files/958972/persistent.txt)

**Comment by theRagingIrishman** [comment]
In the save file it has OldTrait = Kolonist. If you launch Danny he should revert to a Kolonist (USI-LS recalculates stuff when you launch.

**Comment by Baladain** [comment]
placing in vehicle, sending to launch pad and doing an eva did not reset.  Does it require a launch to orbit?

I will follow up with the code change if needed.

**Comment by theRagingIrishman** [comment]
@Baladain no just a launch should be good enough. Are you using the most recent version of USI-LS  and did you update recently (like after accepting the rescue contract but before completing)?

**Comment by Baladain** [comment]
Currently on 0.5.24.0 99% sure I've been on this version since before the contract was accepted.

**Comment by Gnurfos** [comment]
The problem with Danny in that save (preventing him from turning back to a Kolonist) is that, in his stock section, he has: type = Crew, whereas type = Tourist is expected.

I can find no code that could turn a Kerbal into grouchy/tourist without also setting type=Tourist. Do you remember what sequence of events happened to this Danny ? Or maybe, was the save partially edited and type=Crew could have been written manually ?

**Comment by Baladain** [comment]
No changes were made to the save file, that is simply the condition he was
found in when rescued.

**Comment by theRagingIrishman** [comment]
fixed in .52
