### ISSUE TITLE
Add Refining / Assembly specific configs to the Ranger and Tundra ISM's

### ISSUE THREAD

**Issue by FrontLineFodder** [UmbraSpaceIndustries/MKS#1270]
Pull request is coming, Just raising the issue in case more discussion is wanted.

Attached is the table of resources, however here are the displayNames

> Refine Silicon
Refine Polymers
Refine RefinedExotics
Refine Water (Hyd)
Refine Water (Kar)
Refine Water (Ore)
Refine Chemicals
Refine Fertilizer (G)
Refine Fertilizer (M)
Refine Metals
Assemble SpecializedParts
Assemble MaterialKits
Assemble Organics (s)
Assemble Organics (d)
Assemble ColonySupplies
Assemble Machinery
Recycling
Agroponics
Cultivate(S)
Cultivate(D)

[MKS Inflateable list.txt](https://github.com/UmbraSpaceIndustries/MKS/files/960531/MKS.Inflateable.list.txt)

**Comment by FrontLineFodder** [comment]
you want pull requests against the DEVELOP branch don't you ?

**Comment by theRagingIrishman** [comment]
yes please

**Comment by FrontLineFodder** [comment]
i'll figure out how :)

**Comment by theRagingIrishman** [comment]
Steps to making a PR:

- go to https://github.com/UmbraSpaceIndustries/MKS and click the fork button in the top left corner
- then change all the files you want in the new https://github.com/FrontLineFodder/MKS repo (either in the master branch or DEVELOP branch it doesn't matter)
- then go to https://github.com/UmbraSpaceIndustries/MKS/pulls, click New Pull Request, click compare across forks, set base fork to UmbraSpaceIndustries/MKS and DEVELOP and head fork to FrontLineFodder/MKS and whichever branch you used

**Comment by FrontLineFodder** [comment]
sounds easy enough :)

**Comment by FrontLineFodder** [comment]
might want to get the RoverDude to generate moar switchable decals, I ran out after 20 (restarted at 1)
unless he would like to go a different route. I was only planning on adding to the existing configs, not replacing them (don't want to break someone's existing base)

**Comment by theRagingIrishman** [comment]
Changing modules in the .cfg won't affect existing ships (most of the .cfg is copied into the save file) so feel free to replace the old options. If you want more numbers past 20, I could make some more (they're simple .pngs that I could hack together fairly easily), just tell me what numbers you want them to go up to.

**Comment by FrontLineFodder** [comment]
ahh so if we were to remove the current entries, the contents of existing tanks will remain in-changed, but they would no longer be able to EXA and repaint to select that config after the new configs are put in.

Is this what you are saying

**Comment by theRagingIrishman** [comment]
hmm, honestly not sure if FSswitch calls back to original .cfg or the cached version in the save file. If the first, then yes, the tank would stay the old configuration until it was switched for the first time. If the second, all tanks launched before whenever this gets added in would be stuck with the old options for good. let me do a quick test and get back to you on this

**Comment by FrontLineFodder** [comment]
old tanks definably can switch to the new config (just tested)
will test the affect of removing in-use configs from the part file

**Comment by theRagingIrishman** [comment]
alright just did some tests and as far as I can tell changing the config doesn't affect the parts on ships that have been launched so I would say feel free to replace existing configurations

**Comment by FrontLineFodder** [comment]
ok, if you remove the existing entries, the contents remain in-changed
The textures update inline with the new config (ie if the existing tank was set to tank "#4" Refueling-1 it will get the texture associated with new tank entry 4 (in case the DECAL textures change)
in my test texture "#4" was replaced with decal SW_15, the existing tank had that decal when I switch to it.

**Comment by FrontLineFodder** [comment]
theRagingIrishmanNinja

**Comment by theRagingIrishman** [comment]
so do you still want me to make some more numbers or will 20 be enough?

**Comment by FrontLineFodder** [comment]
i'll need moar (say up to "#30" )
I could gimp it, but then they wouldn't be consistent, RD said last night he can make more

**Comment by theRagingIrishman** [comment]
alright sounds good. If you need anything else just lmk

**Comment by FrontLineFodder** [comment]
Are there any plans on retiring the fsFuelSwitch modules and using something more like the moduleconverter methods ?

**Comment by theRagingIrishman** [comment]
afaik no
