### ISSUE TITLE
More Nullrefing

### ISSUE THREAD

**Issue by voicey99** [UmbraSpaceIndustries/MKS#1286]
(this is on 1.52.0-pre from the Constellation)

Several parts (commlab, PDUs, Salamander etc.) have an MKSModule but no BonusEffect specified, this is presumably what is causing them to spew NREs all over the place.

**Comment by voicey99** [comment]
Closing as I, once again, didn't see the new release which fixes this.

**Comment by voicey99** [comment]
Newest release has not fixed all the nullrefs, the heat pump is still spamming the log,

**Comment by BobPalmer** [comment]
Just tested this, can't repro.  What;s the smallest craft this occurs on?

**Comment by voicey99** [comment]
Hm, I can't either. I'm pretty sure this occurred in 0.52.0 (Constellation 1.2 ed.), but I can't see it now. Could be something to do with me accidentally leaving a copy of the MKS git repo in the main KSP dir.

Closing (again). Will reopen (again) if I find it.
