### ISSUE TITLE
invalid CKAN config

### ISSUE THREAD

**Issue by Fumblesneeze** [UmbraSpaceIndustries/MKS#1292]
Hey, I can't seem to be able to install MKS using CKAN. It says "GroundConstruction-Core" is missing. I think that mod is bundled with MKS now, but even if it isn't, the dependency can't be resolved and MKS can't be installed.

**Comment by theRagingIrishman** [comment]
That'll be fixed once Allista updates his CKAN configs do GC for 1.3 (which he put out yesterday)
