### ISSUE TITLE
Kolonist cost is the same as regular hire cost

### ISSUE THREAD

**Issue by strudo76** [UmbraSpaceIndustries/MKS#1297]
Game started in v1.3, using only MKS 0.52.1.0 and USITools 0.9.2.0

[Settings Screenshot](https://drive.google.com/file/d/0B2sHqPR8HJsYY1hXOFJxU2Vab1U/view?usp=sharing)

[Issue Screenshot](https://drive.google.com/file/d/0B2sHqPR8HJsYN01Yd3JGQUNpNm8/view?usp=sharing)

[KSP.log](https://drive.google.com/file/d/0B2sHqPR8HJsYS2RETG9IRk0wWXM/view?usp=sharing)

[output_log.txt](https://drive.google.com/file/d/0B2sHqPR8HJsYbVFfc1ZyVDlTdE0/view?usp=sharing)

Hope that helps!

**Comment by canisin** [comment]
I think I have successfully created a pull request for the resolution of this issue. :)

**Comment by BobPalmer** [comment]
Will be fixed next release
