### ISSUE TITLE
DERP inflatable life pod parachute aerodynamics

### ISSUE THREAD

**Issue by KyleWorden** [UmbraSpaceIndustries/MKS#1310]
Parachute seems to be stuck at 10 spread, and causes life pod to fly sideways. [Pictures](http://imgur.com/a/KjuVZ)

Also, If parachute is deployed before pod is inflated, parachute model will disappear, and re-appear when the craft hits the full-deploy altitude.

**Comment by theRagingIrishman** [comment]
DERP is not part of MKS. Please remake this issue in the correct repo (https://github.com/BobPalmer/ExplorationPack/issues)
