### ISSUE TITLE
Karibou LS support is broken

### ISSUE THREAD

**Issue by voicey99** [UmbraSpaceIndustries/MKS#1337]
All Karibou LS-granting parts default to simply providing 1K-M of habitation time and use no resources, since the ModuleHabitation entry looks to be very obsolete and is missing several key parameters.

**Comment by voicey99** [comment]
Fixed in #1340 (I think).

**Comment by Esendis** [comment]
The rover Cab has been left untreated. Still defaults to 1K-M with no resources.
