### ISSUE TITLE
Rock Resource

### ISSUE THREAD

**Issue by rob-stuart** [UmbraSpaceIndustries/MKS#1342]
Perhaps I am missing something but without the 'Asteroid Recycling Technologies (ART)' mod the 'Rock' resource seems to serve no purpose. I cannot find any resource converters that consume Rock for anything however many converters produce it. Such as the Regolith Sifter, whos sole purpose is to convert either Dirt or ResourceLode into Rock. Same with the Industrial Refinery, each refining process (ie silicates -> silicon) produce Rock as a byproduct.
I realize that by simply not including storage for the Rock resource it will be left out of processes without causing any problems but I just don't see why Rock would be included in processes when ART isn't also installed...
Or is there a converter that turns rock into the other raw resources that I can't seem to find?

**Comment by voicey99** [comment]
Hm, as of 0.53.0 converters should only be outputting Rock if ART is installed. Are you using it?

**Comment by rob-stuart** [comment]
No, I don't have ART installed which is the issue I was bringing up. Without ART the Rock resource serves no purpose as it has no other consumer (that I know of); also the Regolith Sifter only produces Rock, so it too has no purpose when ART is not installed.

**Comment by voicey99** [comment]
Odd, I thought I changed that with PR #1325, included in the latest release. Do all primary (i.e. raw resource refining) converters still do this?

**Comment by voicey99** [comment]
Odd, I thought I changed that with Pull Request #1325 (autolinked to the issue, not PR), included in the latest release. Do all primary (i.e. raw resource) converters still do this?
The sifter doesn't just produce large amounts of rock, it also gives you resources from the dirt based on planetary resource abundance (it doesn't list this in the VAB because it's not constant).

**Comment by rob-stuart** [comment]
Ahh that is my mistake then; I had only looked at the stats given in the VAB assuming that it showed everything that the part could do.
