### ISSUE TITLE
Request: Slim down parts for faster framerates

### ISSUE THREAD

**Issue by nhnifong** [UmbraSpaceIndustries/MKS#1379]
These are some modules that I think would be good candidates for removal:

- command modules and associated trackers modules on structural cradles. Who uses a structural cradle for command? surely your base has a command module on it somewhere else.
- comm uplink modules tundra converters. A large base really only needs one communications dish. If comm modules are pathfinding in the comm network, they could be a hog.

This is just a guess from my own experimentation with my save file. it made a small difference.
If you know of some other factor that would make a bigger difference to framerate for large connected bases, point me in the right direction.

**Comment by tjdeckard** [comment]
The number one contributor to low frame rates is simply part count. The game is running physics calculations on every part and doing them all on a single thread (check your CPU usage while playing KSP and you'll see one core doing most of the work while the others sit mostly idle). So this isn't really an MKS issue. It's a limitation of the game itself, unfortunately. Building several smaller bases that are out of physics range from one another and instead connected via the logistics features of MKS is the only way around the part count limitation currently.

**Comment by mcortez** [comment]
The command on the cradles actually has a purpose as well, it helps prevent a base under construction from being considered debris (vs a vessel.) Being considered debris can cause those parts to garbage collected and pooof, your under construction base vanishes.
