### ISSUE TITLE
Mod crashes when loading (ksp 1.3.1)

### ISSUE THREAD

**Issue by Scythees** [UmbraSpaceIndustries/MKS#1381]
MKS crashes when loading up

I'm using Ksp 1.3.1
i read on other forums it does work on 1.31 like under here
https://forum.kerbalspaceprogram.com/index.php?/topic/154587-13-modular-kolonization-system-mks/&page=250&tab=comments#comment-3241004

I downloaded the mod from here
https://kerbal.curseforge.com/projects/usi-kolonization-systems-mks-oks/files

[error.log](https://github.com/UmbraSpaceIndustries/MKS/files/1778571/error.log)
[output_log.txt](https://github.com/UmbraSpaceIndustries/MKS/files/1778572/output_log.txt)

Please help

**Comment by BobPalmer** [comment]
Curseforge is out of date - get the latest  version from here, also get the most recent USI Tools.

**Comment by tjdeckard** [comment]
I was literally just replying to this. haha

**Comment by Scythees** [comment]
@BobPalmer What are USI tools? I have trouble finding this, unless you mean these? all of these were installed

https://github.com/UmbraSpaceIndustries

Also where does the source folder need to go? (installed in main ksp folder)

when installed some parts are missing, like all the habit modules, fabrication and so on (maybe caused by that USI tools thing) but works otherwise fine

**Comment by tjdeckard** [comment]
It sounds like you may be downloading the source code. You need to download from the Releases section on GitHub:

https://github.com/UmbraSpaceIndustries/MKS/releases
https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/releases

**Comment by tjdeckard** [comment]
We stopped supporting EL in favor of Ground Construction a while back. As far as I know, the parts you mentioned have been deprecated for quite some time now. I suggest you head over to the KSP Forums and ask around there if you have your heart set continuing to use EL. Someone can probably point you in the right direction in terms of how to get EL "back". Understand though that we no longer officially support EL, so if you run into problems getting it to work with MKS, we won't really be able to help.

**Comment by Scythees** [comment]
@tjdeckard I don't necesserally need that mod, but i do need one to build new spaceships, base parts, etc offworld. How do i build these with Ground Construction? (i have trouble finding out how with the wiki and in game)

**Comment by tjdeckard** [comment]
Your questions are getting outside the scope of MKS (and really outside the scope of a Github Issue in general). We provide the core bits of Ground Construction in MKS for the sake of convenience but it is a separate mod maintained by another developer. Head over to the forum thread for Ground Construction for further assistance.

https://forum.kerbalspaceprogram.com/index.php?/topic/154167-131-ground-construction

**Comment by Scythees** [comment]
Thank you, this was exactly what i needed and thanks again for the great support
