### ISSUE TITLE
MKS Tundra Expandable habitation module, can't choose living quarters

### ISSUE THREAD

**Issue by Scythees** [UmbraSpaceIndustries/MKS#1392]
When i try to edit the Tundra Expandable habitation modules (in the rocket build building), then they only give the option to choose the greenhouse, not the living quarters.

Please help

**Comment by Scythees** [comment]
![sdffqsdfqffdssqfdds](https://user-images.githubusercontent.com/37005769/37637085-0cf5b6d0-2c06-11e8-8f47-510855a03f91.png)

**Comment by BobPalmer** [comment]
KSP version?  MKS version?

**Comment by Scythees** [comment]
@BobPalmer Ksp version 1.3.1
MKS version 0.53.0.0
Usi tools 0.10.1.0

**Comment by Scythees** [comment]
This was fixed by reinstalling
