### ISSUE TITLE
Industrial strip miner and MEU-500 drills not loading.

### ISSUE THREAD

**Issue by boiler1** [UmbraSpaceIndustries/MKS#1396]
Industrial strip miner and MEU-500 drills are not loading.  The files are there but something is causing the parts not to load.  Both the automatic and manual versions of each part are not loading.

**Comment by llinard** [comment]
It isn't just the MEU-500 but also the Industrial Strip Miners.  It seems to be unable to replace the textures in those 4 drills (MEU-500, MEU-500A, Industrial Strip Miner, Automated Industrial Strip Miner).

[LOG 09:38:47.762] PartLoader: Compiling Part 'UmbraSpaceIndustries/MKS/Parts/MKS_Drill_02/MKS_Drill_02'
[ERR 09:38:47.763] PartLoader: Encountered exception during compilation. System.NullReferenceException: Object reference not set to an instance of an object
  at PartLoader.ReplaceTextures (UnityEngine.GameObject model, System.Collections.Generic.List`1 textureNames, System.Collections.Generic.List`1 newTextures) [0x00000] in <filename unknown>:0 
  at PartLoader.CompileModel (.UrlConfig cfg, .ConfigNode partCfg, Single scaleFactor, .AvailablePart partInfo) [0x00000] in <filename unknown>:0 
  at PartLoader.ParsePart (.UrlConfig urlConfig, .ConfigNode node) [0x00000] in <filename unknown>:0 
  at PartLoader+<CompileParts>c__Iterator1.MoveNext () [0x00000] in <filename unknown>:0 

[ERR 09:38:47.763] PartCompiler: Cannot compile part

Seems to be related to the following line in the MODEL:

MODEL
{
   model = Squad/Parts/Resources/RadialDrill/TriBitDrill
   **texture = TriBitDrill, UmbraSpaceIndustries/MKS/Assets/TriBitDrill_RD**
   scale = 1,1,1
}

**Comment by NewbieUser123** [comment]
I recently reinstalled all the game with my previous saves and I noticed this issue too.

Is there some solution with this?

**Comment by MaximeBrean** [comment]
You'll have to edit drills cfg files:
- `GameData\UmbraSpaceIndustries\MKS\Parts\MKS_Drill_02.cfg`
- `GameData\UmbraSpaceIndustries\MKS\Parts\MKS_Drill_02A.cfg`
- `GameData\UmbraSpaceIndustries\MKS\Parts\MKS_Drill_03.cfg`
- `GameData\UmbraSpaceIndustries\MKS\Parts\MKS_Drill_03A.cfg`
For each of them, in the MODEL node, you have to comment the texture line. The drills will then load with stock radial texture.

If you want to use custom texture that were previously made for the MKS variants, you can apply this pull request : #1395

**Comment by boiler1** [comment]
Corrected in Pull Request :  #1395
