### ISSUE TITLE
logistics window borked & NRE's

### ISSUE THREAD

**Issue by LouisCyfer** [UmbraSpaceIndustries/MKS#1413]
unsure if this is already reported but I experience some spam while opening the orbital logistics window and the window seems very wrong placed .. like something is not right. (following log I took from the KSP-dev logs)

It happens on planetary overview window and when I click the button at any logistics module I placed at Kerbin (1 landed, 1 in orbit) and 1 at Mun orbit

```
180518T100908.474 [ERROR] [UNKNOWN] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)
180518T100908.563 [EXCEPTION] [KolonyTools.OrbitalLogisticsGuiMain_Module.DrawWindowContents] NullReferenceException: Object reference not set to an instance of an object
   at KolonyTools.OrbitalLogisticsGuiMain_Module.DrawWindowContents (Int32 windowId)
   at KolonyTools.Window.PreDrawWindowContents (Int32 windowId)
   at UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
   at UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```
~~I just can't do any orbital logistics and can't figure how that happened or why so plz any help is appreciated.~~

I figured editing my savefile by cleaning out all transfers (in my case it was only 1 failed transfer) and editing the scenario like this
```
	SCENARIO
	{
		name = ScenarioOrbitalLogistics
		scene = 5, 7, 8
	}
```
did the trick!

I assume either the failed transfer or the vessel-id in that specific transfer made the GUI fail to show correctly so the issue remains for any other changing vessels. Thanks!

**Comment by thegravehunter** [comment]
I'm having the same problem.
whitch file did you edit?
