### ISSUE TITLE
Some parts have strange variants

### ISSUE THREAD

**Issue by Forgilageord** [UmbraSpaceIndustries/MKS#1435]
The Automated Industrial Strip Miner, Industrial Strip Miner, MEU-500 Pulse drill, and MEU-500-A Pulse Drill all have a variant switcher attached to them, containing only one variant; Invariant. The variant cannot be changed, and doesn't seem to affect the part in any way.

**Comment by tjdeckard** [comment]
Look for changes to this in the next release!

**Comment by MaximeBrean** [comment]
This was initially made by me to overcome this problem: #1396 
Those parts use a stock mesh with a custom texture provided by this mod, but basic texture replacement wasn't working.
Using texture variant module was a workaround to apply the custom texture.
