### ISSUE TITLE
1.1 MKS Orbital Logistics appear not to be transferring

### ISSUE THREAD

**Issue by RookFett** [UmbraSpaceIndustries/MKS#1444]
KSP 1.6.1, MM 4.02, latest version of USI modules.  (Hyperedit and Surface lights/KSP-AVC) are also loaded.
Test setup:
Three logistics ships, two landed on Kerbin, (squad monolith KSP), abandoned Airfield, and one LKO 100k.

Initiate transfer of various resources, the resources are deducted, along with Tcredits, but every transfer fails.

Items are lost, along with tcredits.

Repeatable from any of the three points.
[MKS Test.zip](https://github.com/UmbraSpaceIndustries/MKS/files/2857458/MKS.Test.zip)

Included save game, all logs, and craft files.

**Comment by tjdeckard** [comment]
This should be fixed with PR#1445 https://github.com/UmbraSpaceIndustries/MKS/pull/1445
