### ISSUE TITLE
KAS 1.2 update breaks flex o pipes

### ISSUE THREAD

**Issue by menachg** [UmbraSpaceIndustries/MKS#1452]
when updating to kas 1.2 flex o pip will keep parts connected but the options to link/unlink will disappear in the part's functionality

**Comment by JacobRoth** [comment]
I just experienced this as well. Also the pipes themselves are now invisible - still connecting the vessels but the graphics disappeared.

**Comment by menachg** [comment]
actually I observed the pipe disappearing behavior before and they still worked fine so and I don't think it's related to the kas 1.2 update

**Comment by tjdeckard** [comment]
Duplicate of #1461
