### ISSUE TITLE
Comment télécharger MKS sur KSP 1.4.2 ?

### ISSUE THREAD

**Issue by co3yt** [UmbraSpaceIndustries/MKS#1453]
Bonjour/Bonsoir,
Je me présente, je m'appelle Co3 et MKS a l'air de rajouter des trucs super cools ! MAIS je ne sais pas comment télécharger le mod en 1.4.2 car j'ai d'autres mods cools ! si quelqu'un peut m'aider, son aide sera la bienvenue ! merci pour votre contribution. 

Cordialement,
un ingénieur spatial.

**Comment by MaximeBrean** [comment]
Hello,

Tu peux utiliser CKAN, qui devrait te proposer une version compatible avec KSP 1.4.2 (mais probablement pas la dernière version de MKS).
Je te suggère de passer sur KSP 1.6+ (qui est actuellement la version visé par MKS) ou KSP 1.7+ (on devrait surement avoir une version compatible prochainement).

Autre remarque, la communauté autour de KSP est plutôt l'anglophone, tu auras généralement peu de réponse si tu parles dans une autre langue ;)

A+
