### ISSUE TITLE
MKS drills larger sizes "MaxCoolant" not per drillhead

### ISSUE THREAD

**Issue by JBHann** [UmbraSpaceIndustries/MKS#1458]
Each MKS drill only allows a single drillhead to be working per drill because the max cooling matches the required cooling for a single drillhead. Judging by the part description this is not the intended behavior. The mass, cost, and part description for the industrial strip miner indicates it should allow for harvesting 5 resources at a time.

The issue seems to stem from the "MaxCoolant" being defined once for the "ModuleCoreHeat" while each USI_Harvester is defined separately.

I am unclear about the intended behavior of the drills but the current settings yield a required cooling of 100 for each drillhead of the MEU-500 series and 200 per drillhead for the Industrial Strip Miner series. This means to allow simultaneous running of 3 and 5 drillheads respectively:
MKS_Drill_02.cfg and MKS_Drill_02A.cfg line 74 should be changed to "MaxCoolant = 300"
MKS_Drill_03.cfg and MKS_Drill_03A.cfg line 74 should be changed to "MaxCoolant = 1000"

**Comment by tjdeckard** [comment]
Multiple drill heads will be removed in the next release of MKS.
