### ISSUE TITLE
GC ground kit only works, if I install the original mod

### ISSUE THREAD

**Issue by kalmoran** [UmbraSpaceIndustries/MKS#1475]
So I tried to use the MKS ground construction mod, but when I placed any of the kits in the editor, their texture flashed for a split second, then they became simple attachable attachment nodes without any body or textures. The console reported the new added part, showed no error, but the kit's became bodyless. Installing the newest 2.6.0 GC solved the problem. Installed mods:

KSP: 1.8.1

Cryogenic_Engines-1.1.0
RealPlume-Stock_v3.0.1.KSP_1.8.1
KAS_v1.5
KIS_v1.24
ATK_Package_V100061
TweakScale-2.4.3.10
Kerbal_Reusablitiy_Expansion-2.8.5
Trajectories-v2.3.0
ComunityTechTree_3_4_0
MechJeb2-2.9.1.0
KerbalAlarmClock_3.12.0.0
PlanetShine
SCANsat-v18.14
Karbonite_1.3.0.0
KerbalConstructionTime-1.8.0-1.4.7.5-180
USICore_1.3.0.0
CRP_1.3.0.0
ART_1.3.0.0
USITools_1.3.0.0
CCK_5.0.0.0
FTT_1.3.0.0
ExpPack_1.3.0.0
MKS_1.3.0.0
Malemute_1.3.0.0
Konstruction_1.3.0.0
USI-LS_1.3.0.0
Near_Future_Spacecraft-1.3.0
Near_Future_Propulsion-1.2.0
Near_Furute_Construction-1.2.1
Near_Future_Electrical-1.1.0
Near_Future_Solar-1.1.0
Near_Future_Launch_Vehicles-1.3.0
Chatterer-0.9.98

**Comment by tjdeckard** [comment]
Probably old news at this point but GC is no longer bundled with USI.
