### ISSUE TITLE
Reactors don't generate electricity (1.8.1)

### ISSUE THREAD

**Issue by gooseapple5** [UmbraSpaceIndustries/MKS#1478]
I'm using USI with every component installed and none of the reactors work, I've tried them all with them all reaching ideal temperature, them saying they're making power, however the actual power not being generated. I don't have anything that should conflict with it, no kerbal atomics, no NFE or anything like that, I dont know what would be causing it to not generate.

**Comment by tjdeckard** [comment]
I am not able to reproduce this behavior, so it may be a conflict with another mod. Note that reactors will remain idle until the available stored EC drops below 95%. This is by design.
