### ISSUE TITLE
Graphical glitch on the 'Tundra' 2.5M Hub (Short)

### ISSUE THREAD

**Issue by 40thoughts** [UmbraSpaceIndustries/MKS#1482]
Hello,

There seems to be a kind of texture/ligthing glitch on that part, I did notice it on this part and also on the 'Clamp-O-Tron construction port'.

Basically, the parts seem a bit strange in the VAB/SPH, totally normal when on a dark side of a body, and partially or totally black (as unaffected by light) when the vessel's hit by the sun.
I also just noticed while taking the screenshots that it's way brighter when looked from behind on the top half of the hub (with the sun's in front of the camera).

I'm playing on Ubuntu 20.04, KSP 1.8.1, NVIDIA GeForce GTX 1660 Ti.
Heavily modded, so this could be on my end only but apart from the 'ReStock' mod I don't have any other mod that's affecting visuals/textures.

VAB :
![VAB_BUG](https://user-images.githubusercontent.com/6198621/85320504-72734200-b4c3-11ea-8afe-adafefd04aea.png)

Dark Side :
![Space_DarkSide_BUG](https://user-images.githubusercontent.com/6198621/85320500-70a97e80-b4c3-11ea-988f-e1ca75e57d68.png)

Sun Side :
![Space_Sun_BUG](https://user-images.githubusercontent.com/6198621/85320502-71daab80-b4c3-11ea-8118-13ed23fafc97.png)

On the screenshot below, the 'Clamp-O-Tron Construction Port' is mounted on the faulty '2.5M Hub' on the right and there's a stock 'Clamp-O-Tron' on the left of the Hub which seems totally fine :
![Clamp-O-Tron_BUG](https://user-images.githubusercontent.com/6198621/85323788-f54acb80-b4c8-11ea-820f-b43727440a80.png)

By the way, I tried the other 2 'Clamp-O-Trons' from your mod and they seem to render just like normal so no problem there.

**Comment by tjdeckard** [comment]
A fix for this will be included in the next release
