### ISSUE TITLE
Karibou wheels too torquey

### ISSUE THREAD

**Issue by somnambulistic** [UmbraSpaceIndustries/MKS#1483]
The torque curve on the Karibou wheel needs to be updated to *greatly* reduce the low-end torque. iirc several versions ago the extra bottom-end torque was required to even get moving but, as of 1.9, it just makes it possible to put even the heaviest of rovers up on two wheels under 1g or even flip end-over-end on the Mun. 

Current torque curve:

```
torqueCurve
	{
		key = 0 100.0 0 0
		key = 1.0 30.0 0 0
		key = 5.0 15.0 0 0
		key = 20 5.0 0 0
		key = 36 0.5 0 0
		key = 38 0 0 0
	}
```
Proposed torque curve:

```
torqueCurve
	{
		key = 0 2.0 0 0
		key = 1.0 30.0 0 0
		key = 5.0 15.0 0 0
		key = 20 5.0 0 0
		key = 36 0.5 0 0
		key = 38 0 0 0
	}
```

**Comment by tjdeckard** [comment]
Adding this to the next release.
