### ISSUE TITLE
LightGlobe part causes game launcher to hang [KSP 1.10, UKS 1.3.0.0]

### ISSUE THREAD

**Issue by DungeonMaestro** [UmbraSpaceIndustries/MKS#1485]
Like it says in the title, before deleting UmbraSpaceIndustries/MKS/Parts/LightGlobe.cfg the game launcher hangs at that part. After removing it the game launches successfully; it's just the one part seems to be critically incompatible. I'm aware the mod isn't supported on the new version of KSP yet; I decided to try anyway and am here to report a finding. If there's a better place to report incompatibility findings with the new game version lemme know

**Comment by Megalozavr** [comment]
Got the same issue (

**Comment by Geowil** [comment]
Same problem, getting this in the ksp log file:

[LOG 18:56:51.003] PartLoader: Compiling Part 'UmbraSpaceIndustries/MKS/Parts/LightGlobe/MKS_LightGlobe'
[WRN 18:56:51.013] Part already contains  resource 'ElectricCharge'
[LOG 18:56:51.020] PartLoader: Part 'UmbraSpaceIndustries/MKS/Parts/LightGlobe/MKS_LightGlobe' has no database record. Creating.
[LOG 18:56:51.020] [DragCubeSystem]: Drag cubes not found or cannot be read for part Part. Generating New drag cubes.
[LOG 18:56:51.024] DragCubeSystem: Creating drag cubes for part 'MKS.LightGlobe'
[EXC 18:56:51.081] NullReferenceException: Object reference not set to an instance of an object
	ModuleDeployablePart.AssumeDragCubePosition (System.String name) (at <c168e21ec56346b082f89043e76162e1>:0)
	DragCubeSystem+<RenderDragCubes>d__34.MoveNext () (at <c168e21ec56346b082f89043e76162e1>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by BobPalmer** [comment]
Sorted this in the next release.

**Comment by Sylvrwynd** [comment]
Is it a configuration file fix? Is it something I can implement while awaiting the next release? I would prefer not to remove this part if possible.

**Comment by 7ranceaddic7** [comment]
Nope. I you look at the commit history, you'll see an update 5d ago. It's not a config issue, it's a dependency.

**Comment by BobPalmer** [comment]
Not a dependency, had to do a slight re-ordering of the config.

**Comment by 7ranceaddic7** [comment]
And, that's what I get for not paying attention to which branch I'm looking at.

**Comment by metalbass** [comment]
I've just installed this over ksp 1.10 (using CKAN) and it fails exactly as described by the OP.

I guessed I'd need to download the latest version from the develop branch over the installed mod, but no luck.
This is the commit I was hoping would fix the issue: https://github.com/UmbraSpaceIndustries/MKS/commit/2fc917f1332e2fd3e1208db35cfad55092564b0b

I may done something wrong, if this should have worked.

Finally, removing the LightGlobe part file "fixed" it, but to be honest, I don't know what I removed 😅

**Comment by Geowil** [comment]
@BobPalmer Any idea at a timeline when this fix will be pushed to the dev branch?  Is it something we could undertake fixing ourselves individually in the mean time or did the fix require more than just an edit to the LightGlobe cfg?

Thanks!
