### ISSUE TITLE
A lot players want localized MKS/USI

### ISSUE THREAD

**Issue by leslie-yih** [UmbraSpaceIndustries/MKS#1486]
Though I can read English, but MKS/USI is a very complicated mod. It's difficult to learn all the contents and react quickly when something goes wrong. A lot player volunteer to localize the mod, so I wonder if author could provide localization interfer.

**Comment by tjdeckard** [comment]
As you say, MKS is a very complicated mod and going back to add localization support at this point would also be a major undertaking. I believe there has been some work done by another community member but I'm not sure it ever got finished. Also, the upcoming WOLF addition to the USI suite does have localization support. So there are at least some examples of _how_ to do the localization if someone wanted to spearhead the project and submit a pull request. It's not on the roadmap for Roverdude or myself to do that though.
