### ISSUE TITLE
Akademy levels not limited

### ISSUE THREAD

**Issue by JohnR6** [UmbraSpaceIndustries/MKS#1493]
On KSP version 1.10.1, MKS 1.3.0.0

I was planning on sticking an akademy module on my orbital station, but I decided to test it on kerbin first to make sure I knew how it worked (first time with the mod). I slapped an akademy module on the runway with a battery pack and two kerbals, one level 4 and the other level 0, and clicked 'Start Training'. Instantly the level 0 kerbal was level 4. The wiki says kerbals in Kerbin akademies aren't supposed to be able to go over level 1, so this seems wrong (it definitely feels busted).

**Comment by tjdeckard** [comment]
Fixed in the linked PR... I think.
