### ISSUE TITLE
Ksp fails to load

### ISSUE THREAD

**Issue by Lexray12** [UmbraSpaceIndustries/MKS#1494]
When using USI MKS my game gets suck on loading "UmbraSpaceIndustries/MKS/Parts/LightGlobe/MKS_LightGlobe", Left it for 1/2 hour, came back, still suck on loading that specific bit. Have re-installed twice, same issue. No idea if this is a bug or what, shouldn't be a conflict as I'm using someone else's Mod set and they didn't seem to have any issues. I've installed using CKAN.

**Comment by ttr** [comment]
Manual fix described here:
https://forum.kerbalspaceprogram.com/index.php?/topic/154587-18x-modular-kolonization-system-mks/page/384/&tab=comments#comment-3863703
