### ISSUE TITLE
Parts not loading

### ISSUE THREAD

**Issue by szlachta99** [UmbraSpaceIndustries/MKS#1510]
So i've downloaded a couple of mods including MKS and it looks like it doesn't work. I've checked my files a couple of times and looked for any updates. Nothing seems to be working. I play on 1.11 ksp with both DLC's if it matters.

**Comment by BobPalmer** [comment]
You are providing almost no information.   Best place to ask stuff like this is going to be in the MKS forum thread and provide info there.
