### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Tacombel** [UmbraSpaceIndustries/MKS#1516]
The kerbal in the module is an engineer
![image](https://user-images.githubusercontent.com/17971083/107143503-b6716500-6935-11eb-9afc-758d383ddf20.png)

**Comment by tjdeckard** [comment]
I'm not able to reproduce this behavior. It may have already been fixed. Can you confirm this is still happening and if so, list the steps necessary to reproduce the error?

**Comment by Tacombel** [comment]
I will check, but I think I deleted that save.
