### ISSUE TITLE
Request: more scaling in WOLF scanning rewards sliders

### ISSUE THREAD

**Issue by EleSigma** [UmbraSpaceIndustries/MKS#1526]
I would like to request that the WOLF scanning reward sliders be able to be scalable to 0. As of now the biome resource scanner, at its lowest level gives an instant 10 research points for the homeworld and 50 for offworld per-biome. For players that like a challenging career this can be game breaking since it does not scale to other research settings.

Is it also possible, for an option, to tie the WOLF resource scanner's research into the stock research system so that it does scale to what career research settings a player has set for their career?

**Comment by tjdeckard** [comment]
Sliders have a min value of 0 in the linked PR. I'm not sure what you mean though about tying the WOLF scanner into the stock research system. Can you give more detail?

**Comment by EleSigma** [comment]
Thanks for taking time to respond! By stock I mean having to store, then send or recover the scientific data instead of it immediately being deposited back to the space center the moment you run the test, like it is currently.
