### ISSUE TITLE
Request: Konstructor Materials Configuration for Storage

### ISSUE THREAD

**Issue by myj99** [UmbraSpaceIndustries/MKS#1527]
There's 5 specialized materials that are only used for Konstructor, and some vessels require all 5, except in rather miniscule quantities. At present, that means that Konstructor ships need up to 7 unique parts all devoted exclusively to storing resources.

The inflatable storage module configurations seem to fill the niche of holding many different resources required in the same process all in one part, and seems the most appropriate for a part that can hold the 5 Konstructor resources all together. 

In addition, for materials delivery, it would be nice to be able to deliver the specific resources needed for Konstructor in a single package to bases which are capable of producing some, but not all, materials in-situ. Having a Kontainer config for this would also be helpful to Konstructor users, although it'd be a second exception to the rule that Kontainers only hold 1 resource at a time.

**Comment by tjdeckard** [comment]
We'll add something for this in the next release.
