### ISSUE TITLE
NRE preventing creation of WOLF Crew Transfer UI

### ISSUE THREAD

**Issue by Grimmas** [UmbraSpaceIndustries/MKS#1530]
Steps to reproduce: 
1) install clean stock KSP 1.11.2
2) install USI Constellation pre-release or install freshly compiled from source
3) start or load a game

It may or may not happen for you as it's not clear to me whether this is deterministic behavior. But it happens for me every time.

The issue is in WOLF_CrewTransferScenario.OnAwake() method - FindObjectOfType<WOLF_ScenarioModule>() returns null and the NRE happens in the subsequent call to wolfScenario.ServiceManager.GetService()

Seems like WOLF_ScenarioModule is only created afterwards and therefore can't be accessed that way in WOLF_CrewTransferScenario

Here's the log output - with a few debug comments from me added to the offending methods:

[LOG 02:15:10.169] [AddonLoader]: Instantiating addon 'WOLF_ScenarioMonitor_SpaceCenter' from assembly 'USI_WOLF'
[LOG 02:15:14.027] [UIMasterController]: HideUI
[LOG 02:15:14.440] [ScenarioDestructibles]: Loading... 0 objects registered
[ERR 02:15:14.452] entering CrewTransferScenario.OnAwake

[ERR 02:15:14.453] calling FindObj

[ERR 02:15:14.457] wolfScenario is null

[EXC 02:15:14.462] NullReferenceException: Object reference not set to an instance of an object
	WOLF.WOLF_CrewTransferScenario.OnAwake () (at <4dacc9ee3fb9484daf799ec85d486799>:0)
	ScenarioModule.Awake () (at <06f13185617646e5bc801baeab53ab75>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.GameObject:AddComponent(Type)
	ScenarioRunner:AddModule(String)
	ScenarioRunner:AddModule(ConfigNode)
	ProtoScenarioModule:Load(ScenarioRunner)
	ScenarioRunner:LoadModules(List`1)
	ScenarioRunner:SetProtoModules(List`1)
	Game:Load()
	<Start>d__4:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[ERR 02:15:14.463] entering WOLF_ScenarioModule.OnAwake

[LOG 02:15:14.471] [CustomConfigsManager] Setting modded tech tree as the active one

Full KSP.log attached - 
[KSP.log](https://github.com/UmbraSpaceIndustries/MKS/files/6347299/KSP.log)
  
Edit: I should add that this affects not only the initial space center but that this behavior persists across every scene change, preventing the WOLF Crew Transfer UI from ever showing up.

**Comment by RookFett** [comment]
Seeing this same issue with the latest pre-release and MKS bleeding edge.

**Comment by tjdeckard** [comment]
This has been fixed in the latest pre-release and will be available in the next stable release.
