### ISSUE TITLE
Capitalization error in MKS_CTT.cfg causing misplaced small atlas harvesters in tech tree

### ISSUE THREAD

**Issue by dlrk2** [UmbraSpaceIndustries/MKS#1532]
In MKS_CTT.cfg, 

`@PART[ATLAS_Harvester_sm*]:NEEDS[CommunityTechTree]
{
	@TechRequired = colonization
}`

should be 

`@PART[ATLAS_Harvester_Sm*]:NEEDS[CommunityTechTree]
{
	@TechRequired = colonization
}`

**Comment by tjdeckard** [comment]
Thanks. This will be fixed in my next PR.
