### ISSUE TITLE
Buggy lighting on Flex-o-tubes [1.11.1]

### ISSUE THREAD

**Issue by sossololpipi** [UmbraSpaceIndustries/MKS#1535]
![kolonytubes](https://user-images.githubusercontent.com/43117641/117895483-6c798180-b28c-11eb-9c69-6861ac6d77dc.PNG)

as you can see on this picture, flex-o-tubes do not have their "connection" part lit up when their bases are.

**Comment by tjdeckard** [comment]
Flex-O-Tubes are unfortunately deprecated and won't be receiving updates.
