### ISSUE TITLE
new to mks everytime I try to expand a inflatable

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [UmbraSpaceIndustries/MKS#1538]
I can expand them in the VAB  whenever I get to the launch pad  does not work

**Comment by notthebobo** [comment]
Welcome to the mod, you have a fun path of learning ahead. 
The inflatables need to be deployed from EVA and some require MAterialKits. 
Best place to ask questions is the [forum](https://www.google.com/url?q=https://github.com/UmbraSpaceIndustries/MKS/wiki&sa=D&source=editors&ust=1624987944995000&usg=AOvVaw1BqVt9UtpX4GLqJ-FME6f8). There are also good resources on the [Wiki](https://github.com/UmbraSpaceIndustries/MKS/wiki), such as [this section](https://github.com/UmbraSpaceIndustries/MKS/wiki/Parts-%28Ranger-Series%29#crewed-modules) that discusses your issue.

**Comment by REVIEWGAMINGMAN** [comment]
https://imgur.com/a/mnuRGxy

**Comment by MaraRinn** [comment]
From your image it looks like you're confusing the "EVA Repair Kit" with the Modular Kolonisation System resource "Material Kits".

Take your ship back into the VAB and look under the "Logistics" group (it has a Forklift icon) for Kontainers.

The message that shows up is indicating what you need to provide in order for your Kerbal to be able to expand the habitat: 1000 MaterialKits and 100 electric charge.

![kontainers_to_hold_MKS_resources](https://user-images.githubusercontent.com/43090/137586866-2b63c786-3c5e-4f67-abe8-5cebad345a1c.png)

Resource management with MKS involves clicking a lot of "Next cargo" buttons. In that image I've clicked "Next Cargo" 6 times to cycle through "Metallic Ore" -> "Uraninite" -> "Substrate" -> "Minerals" -> "Karbonite" -> "Exotic Minerals + Rare Metals" -> "Material Kits".  Then adjust the quantity of Material Kits to at least 1000 to give you enough Material Kits to deploy the habitat. Then you'll need to supply power, so add a battery such as the Z-1K Rechargeable Battery Bank. Then for ongoing operation of the habitat you'll need to provide "Machinery" (a few units a day).

You can read more about MKS in the KSP forum thread here: https://forum.kerbalspaceprogram.com/index.php?/topic/154587-111x-modular-kolonization-system-mks/
