### ISSUE TITLE
Latest Version does not work with KSP V1.12.1

### ISSUE THREAD

**Issue by joannplano2005** [UmbraSpaceIndustries/MKS#1539]
The latest Version locks up KSP V1.12.1. It prevents all of the modules including Squad.

**Comment by BobPalmer** [comment]
I am currently using the constellation with 1.12.1 - so I would need more specificity.

**Comment by joannplano2005** [comment]
If I put the lastest MKS into the game and then start the game, No modules load. You do not see any loading in the load line. If I take MKS out, all the modules load, you see them on the load line.
JoAnn DonaldsonAB8YZ
    On Tuesday, July 6, 2021, 01:31:16 PM CDT, Bob Palmer ***@***.***> wrote:  
 
 


I am currently using the constellation with 1.12.1 - so I would need more specificity.

**Comment by BobPalmer** [comment]
Sorry - again, I am literally running the current constellation pre-release (which includes MKS) on 1.12.1 without issue.  So it sounds like you have a conflict.  Also, note that while the current constellation pre-release works in 1.12.1, I can't guarantee the current MKS Stand-alone.  Lastly, make sure Module Manager is installed.

**Comment by joannplano2005** [comment]
Module Manager is installed. I will run it again with MKS installed and see if it is just that the text is not running on the screen. If the game comes up then I am a Happy Camper.
JoAnn Donaldson   On Tuesday, July 6, 2021, 01:56:14 PM CDT, Bob Palmer ***@***.***> wrote:  
 
 


Sorry - again, I am literally running the current constellation pre-release (which includes MKS) on 1.12.1 without issue. So it sounds like you have a conflict. Also, note that while the current constellation pre-release works in 1.12.1, I can't guarantee the current MKS Stand-alone. Lastly, make sure Module Manager is installed.

**Comment by joannplano2005** [comment]
Bob,    Finally discovered why my KSP V1.12.1 was not loading. It was NOT your program at all. It turned out that the Stock Visual Enhancements had a sub folder for your program. I deleted that sub folder and BINGO, KSP V1.12.1 loaded and Kerbal's Atmosphere switched to the enhanced mode. I will look further into that Sub Folder and see if it is one particular file or what. All of your main modules are working great. Don't really need the Texture files for your modules as they look great as is.
JoAnn Donaldson  

    On Tuesday, July 6, 2021, 1:31:16 PM CDT, Bob Palmer ***@***.***> wrote:  
 
 


I am currently using the constellation with 1.12.1 - so I would need more specificity.
