### ISSUE TITLE
MKS dirlls have a bug

### ISSUE THREAD

**Issue by Konstantine233** [UmbraSpaceIndustries/MKS#1541]
Some MKS drills have a bug that they only have one bay can use. For example, the Industrial Strip Miner should have 5 bays but now in game it only has one bay. The KSP version is 1.11.2 and the MKS version is 1.4.1. There're no other non-USI mods installed.

**Comment by tjdeckard** [comment]
Multiple bays on drills have been deprecated. They caused a lot of confusion for players due to the way heating works. All MKS drills should now only have a single bay.
