### ISSUE TITLE
WOLF Cargo Container and Crew Cargo Container: Payload on transport computer goes to 0 after docking the ship

### ISSUE THREAD

**Issue by diegogalati** [UmbraSpaceIndustries/MKS#1544]
It happens randomly on the same ship that after docking it to another ship containing a WOLF fuel hopper in orbit, the payload recorded on transport computer goes from initial value to 0. This impede to complete a WOLF route, since the payload disappears

**Comment by RookFett** [comment]
I will have to test this one - but you do not have to dock to make a transport route to LKO depot - just be in a stable orbit.  I would suspect that root change may be the culprit though (just spit balling here)

**Comment by diegogalati** [comment]
Thanks for the reply! I need to dock in order to refuel and lowering (or bring to 0) the transport credits required to make the route. I'll check about your root change hypothesis

**Comment by RookFett** [comment]
Well your in luck - you can use the Wolf Logistics Transfer resources (the little forklift icon on the toolbar) to re-fuel without docking, as long as you are in range.

**Comment by tjdeckard** [comment]
What @RookFett  said.
