### ISSUE TITLE
Wolf Crew Transfer UI and Button is not loading and causing NRE in logs

### ISSUE THREAD

**Issue by RookFett** [UmbraSpaceIndustries/MKS#1545]
When running the latest KSP 12.2 and Constellation 2021.03.12.01 mod only, upon getting to a scene with the crew transfer button, it will not display, and the PAW menu item will not do anything upon clicking it.   Check of the logs shows a NRE with the WOLF.WOLF_CrewTransferScenario function consistently.
Logs attached (clean install with no mod and Constellation installed).

I have tried 4 different computers, fresh installs of KSP and Mod, AV turned off, processes refined to avoid interference, all do the same issue.  I also ran through all the pre-release versions of USI and MKS, fresh install each time, same issue.   Windows 10 and Windows 11 tested.

There are some users reporting that they can see the button and use it successfully and there are users that see what I am observing.

I have observed that the Resource Transfer button will not show unless I change scene and come back to it, after that, it will stay.   If I restart KSP, I have to change scene again to see it.

Everything else in Wolf appears to be working, resource routes and transfers.   I can make crew routes, and if I check the save file, they are there, listed as "boarding", it's appears that just the Wolf Crew UI is not working.

[KSP Constellation Error.zip](https://github.com/UmbraSpaceIndustries/MKS/files/7196600/KSP.Constellation.Error.zip)

**Comment by tjdeckard** [comment]
This has been fixed in the latest pre-release and will be available in the next stable release.
