### ISSUE TITLE
Messaging on Screen when attempting Luxury route has error if you do no have the resources

### ISSUE THREAD

**Issue by RookFett** [UmbraSpaceIndustries/MKS#1551]
Latest build MKS.

Trying to make a luxury crew route between terminals, have a message pop up stating **"Origin depot need an additional ({0}) ColonySupplies to support this route."**

It doesn't tell you how much you need, so I hacked the save till I found the number I needed to make it work,
Looks like the variable string is not pulling as it should.

**Comment by tjdeckard** [comment]
This will be fixed in the next release.
