### ISSUE TITLE
Karibou Modular Wheel Steering is "floppy" and unstable

### ISSUE THREAD

**Issue by Codebreakerblue** [UmbraSpaceIndustries/MKS#1559]
**KSP version:** 1.12.3, Windows 10 64-bit
**MKS version:** Unstable Release 112.0.1-bleeding-edge.3

**Description:**
The Karibou Modular Wheel behaves oddly. While moving forward, the steering barely responds to input. When steering left or right for an extended period, the wheels start to steer more and more in that direction and stop responding to input altogether. Retracting and extending the wheels resets their orientation.

_(note the yaw input display in the bottom left)_

https://user-images.githubusercontent.com/18739767/166126858-14355c4e-833c-4908-8146-42352611d582.mp4

**Comment by zajc3w** [comment]
It is just enough to drive forward a bit and wheels do 360 spins(on steering axis) on their own.
same problem in KSP 1.2.4,  1.2.2 and 1.2.3
MKS version 1.2.0.1 stable and bleeding edge 4 releases

fix for the issue, basicaly slightly teweaked maleute wheel config entries:
```
MODULE
	{
		name = ModuleWheelSuspension
		baseModuleIndex = 0
		suspensionTransformName = suspensionPivot
		maximumLoad = 40.0	
		suspensionDistance = 0.125
		targetPosition = 0.5
		springRatio = 7
		damperRatio = 1.0
	}
	MODULE
	{
		name = ModuleWheelSteering
		baseModuleIndex = 0	
		caliperTransformName = SteeringPivot		
		autoSteeringAdjust = true
		steeringResponse = 1.5
		
		steeringRange = 35
		
		steeringCurve
		{
			key = 0 20
			key = 20 20
		}
		steeringMaxAngleCurve
		{
			key = 0 1 0 0
			key = 3 1 0.0001624425 0.0001624425
			key = 7.5 0.33 -0.05674612 -0.05674612
			key = 20 0.12 -0.003158088 -0.003158088
			key = 30 0.1 -0.002872917 -0.002872917
		}
	}
```
edit:
GameData\UmbraSpaceIndustries\Karibou\Parts\KER_Wheel_01.cfg
and swap two above modules.
or cpy this file :https://drive.google.com/file/d/1dsjaDXgCHkBkwbjqJZ41EUJp6w8k0bZ3/view?usp=sharing

**Comment by Codebreakerblue** [comment]
Oh wonderful. Thank you!

**Comment by ArminGholampour** [comment]
I have the same problem 
Replacing the codes did not solve my problem 
My game version is 1.12.5

**Comment by zajc3w** [comment]
I didn't play with that mod in ages, I don't think that much has changed
since then though. Are you sure you saved your changes and restarted the
game?

**Comment by ArminGholampour** [comment]
I have replaced and saved all the codes
I just edited the file again (maybe it was my mistake) and I will test it again

**Comment by ZoeESummers** [comment]
> I have replaced and saved all the codes I just edited the file again (maybe it was my mistake) and I will test it again

Did that work?!

**Comment by Tesseractcubed** [comment]
Had this issue, replaced code segments (the two modules for suspension and steering) and that solved the issues with steering. (1.12.5 with lots of mods).
