### ISSUE TITLE
WOLF Resources should be exposed to the player in cfg files.

### ISSUE THREAD

**Issue by ProgrammerFailure** [UmbraSpaceIndustries/MKS#1580]
Currently, the WOLF Resources seem to be defined in the actual code of the mod. Ideally, they would be defined in cfg files, with something like a WOLF_RESOURCE node.

 Distributions could be defined in  WOLF_PLANETARY_RESOURCE or WOLF_GLOBAL_RESOURCE nodes. 

This would allow adding custom recipes for WOLF, customizing WOLF through MM patches, and turning it into a framework for abstracted resource gathering. It would also let mods use WOLF for their own needs.

I think this would be really useful and improve the player experience.

**Comment by tjdeckard** [comment]
> Currently, the WOLF Resources seem to be defined in the actual code of the mod. Ideally, they would be defined in cfg files, with something like a WOLF_RESOURCE node.

Nope. WOLF uses CRP (CommunityResourcePack) just like MKS and many other mods. If a resource is available in CRP, it's available to WOLF.

> Distributions could be defined in WOLF_PLANETARY_RESOURCE or WOLF_GLOBAL_RESOURCE nodes.

Resource distributions are based on the stock resource distributions, which are informed by CRP for non-stock resources. The planetary and global distributions can already be adjusted via `.cfg` files.

> This would allow adding custom recipes for WOLF, customizing WOLF through MM patches, and turning it into a framework for abstracted resource gathering. It would also let mods use WOLF for their own needs.

This is already possible. The recipes in WOLF are setup in the `.cfg` file for each WOLF part. Other config options are available in the `WOLF.cfg` file in the root of the WOLF folder.

**Comment by ProgrammerFailure** [comment]
@tjdeckard 
Could you clarify where I can add my own resources? For example, I want to add WBI graviolium to WOLF. How do I do that? Can it only support CRP? I.E, is it hardcoded for CRP?

**Comment by tjdeckard** [comment]
If you're wanting to create brand new resources that don't already exist in CRP, there is a way to do that but I don't remember how off the top of my head. It's just a config file, iirc. CRP builds on top of the stock resource system in KSP. So CRP would actually be a good place to look to figure out how to add your own resources, set their abundance, etc. If you can get the stock resource system to see your resource as a resource, then it can be used in WOLF (...after you add it to `AllowedHarvestableResources` in the WOLF.cfg file and create MM patches to add recipes for it to the harvesters, converters, etc.).

Side note: If you aren't already on the USI Discord, you might want to pop in. https://discord.gg/FNBwUXRgX8. I'm more likely to see stuff there before I see it on Github.

**Comment by ProgrammerFailure** [comment]
Ok yeah, i had seen the allowedHarvestebleResources thing, but since wolf resources used DirtVein instead of Dirt, I thought that DirtVein was a different resource defined in the mod. 

Thanks for your help, this fixes my problem completely. 

Will test soon, sorry to bother you. Is MKS still developed?
