### ISSUE TITLE
Notification of Logistics Hub Inactivate-ability

### ISSUE THREAD

**Issue by ghost** [UmbraSpaceIndustries/MKS#195]
The logisitics hub doesn't work if the vehicle is in "Pre-Flight" state, however there is no visual indication of this. Instead the "New Transfer" button just does nothing (produces an IndexOutOfRange exception) if clicked before the vessel has been physically launched.

It would be helpful if there were a visual notice telling the user that the hub cannot be used until it is launched, using, for example, the green lettering which Science experiments use to convey that they don't work in the current situation or biome.

**Comment by Stikkychaos** [comment]
Seems like i have encountered the same issue. My first logistics hub works fine, while the second one(s) have non working "new trasfer" button. Neither on the surface, nor on the orbit. 
Has anything been done in the regard?

**Comment by joshbenner** [comment]
I'm seeing this behavior:
1. Build Ship w/ Logistics Hub
2. Launch to Kerbin SOI
3. New Transfer window opens successfully
4. Navigate to Mun orbit
5. New Transfer window does not open, IndexOutOfRangeException observed in logs
