### ISSUE TITLE
Logistic Hub & NaN

### ISSUE THREAD

**Issue by Mireru** [UmbraSpaceIndustries/MKS#262]
Current Scenario:

On Minmus there are two Colonies.  Both have a Logistics Hub. 
There are three satellites in equatorial orbit at 2,000km.
There is a satellite in polar orbit at 150 km. 
Dotting the surface are various crashed rocket stages (intact though).

Either Colony can start a logistic transfer from any ground location to orbit.
Either Colony can start a logistic transfer from orbit to any ground location.
Either Colony can start a logistic transfer from any orbital sat to any orbital sat.
Either Colony can start a ground transfer from any non-colony ground rocket to any non-colony ground unit.

Any time a colony is involved in a ground transfer (be it sending or receiving) the fuel consumption cost will be NaN, regardless if Liquid Fuel or Karbonite.

---

Testing on Kerbin, where an identical Colony exists at the south pole, it was capable of being involved in ground-to-ground transfers. Setting up a second Logistics Hub did not interfere, and they could send to each other, even if one were in Prelaunch state.  Setting coordinates of one to 0,0 had no effect either (pertinent as one of the Minmus Colonies lies close to 0 lat, 0 long).

Returning to Minmus, Hyperediting one colony into orbit didn't change anything.   Destroying one of the Logistic Hubs changed nothing. Hyperediting to an altitude that wasn't 0m changed nothing. 

RemoteTech status of the other ship (i.e. 'online' or 'not connected) did not change a working transfer to NaN, or a NaN to one that would work.

---

Reloads of saved game, and reloads of the client changed none of the above results.

I'd wonder if it's possible to just have two bugged ships?

**Comment by mnybon** [comment]
I can verify this problem. And its not just minmus either:)

**Comment by glennfu** [comment]
I have a Logistics hub at 100km, 0 inclination around Kerbin, and a ship 108km, 5.4 inclination around Kerbin, and I get NaN trying to transfer.
