### ISSUE TITLE
Logistics Hub transfer status: Nan 

### ISSUE THREAD

**Issue by Prototype2001** [UmbraSpaceIndustries/MKS#286]
My surface Minmus base has a logistics hub which can't retrieve anything from surface to surface however it works fine orbit -> surface  surface -> orbit transfers.

Edit: Adding a second logistics hub to Minmus Orbit yields the same results, can't seem to transfer surface-> surface with any combination.

**Comment by mnybon** [comment]
I can verify this problem.
The problem starts when within the transfer hub dialog. The moment you select any resource from transferable resources, or press either the LFO or karbonite buttons, the fuel counters shows "NaN". If you send the goods anyway, the transfer is initiated with an infinite counter.

**Comment by koshboo** [comment]
am also having this problem when it does it this is in the log
[Exception]: ArgumentException: Getting control 0's position in a group with only 0 controls when doing mouseUp
Aborting

had a look in google and found this
http://answers.unity3d.com/questions/400454/argumentexception-getting-control-0s-position-in-a-1.html

**Comment by mnybon** [comment]
For orbit/orbit transfers,  it might just be that the orbits of the two
craft are to different.  Large differences in inclination,  for example,
seems to lead to the nan message too.

This could do with slightly bettet feedback,  if its not too much trouble:)

**Comment by richardhendricks** [comment]
Yes, the same issue comes up when in a hyperbolic orbit - even if the SoI departure is days out, you can't transfer to it.

**Comment by mnybon** [comment]
It really would be helpful with a status message in the transfer planner
that feeds this info to the player. You really have no idea whats wrong or
how to fix it.
