### ISSUE TITLE
Orbital logistics transfers not arriving at destination vessel unless active at the time of arrival

### ISSUE THREAD

**Issue by basedrifter** [UmbraSpaceIndustries/MKS#310]
This was a problem in previous versions and still appears to be an issue. If I send an orbital logistics supply from my Minmus Outpost to the orbiting ship the supplies will not arrive unless the destination vessel is active when the supply "arrives." If I leave the Minmus Outpost that is sending the resources as active until after the transfer is completed, then switch to the destination vessel, the supplies vanish and do not arrive.

**Comment by geoffromer** [comment]
Have you experienced this bug since OKS 0.22.4 was released? I'm not immediately able to reproduce it, and there were some changes to orbital logistics in that release that might have fixed it.
