### ISSUE TITLE
Part Request - integrated Mk3 landing system

### ISSUE THREAD

**Issue by basedrifter** [UmbraSpaceIndustries/MKS#311]
With the new Mk3 units, they lack an awesome all in one landing solution like the Mk2 modules have. What I ended up doing was using two FTT end caps with 4 landing gear attached to them. This was the cleanest (and best looking) arrangement I could come up with. However this results in a part count that is more than doubled compared to the Mk2 modules.

Mk2: Module, base, two Flex-tube connectors = 4 parts per module landed.

Mk3: Module, two end caps, 4 landing gear, 2 Flex-tube connectors = 9 parts landed. 

So where with the old system it would be 16 parts to land a refinery, machinery plant, fabrication plant, and repair modules under the Mk2 system, the Mk3 system uses 36 parts.

It would be awesome if you could make an end cap for the Mk3 modules that includes landing gear. That would save 16 parts in landing gear for all four Mk3 modules.

**Comment by HorusAK** [comment]
And later there will a request for end caps with integrated wheels - for mobile bases :) JK
