### ISSUE TITLE
Pump In + Pump Out

### ISSUE THREAD

**Issue by Felson** [UmbraSpaceIndustries/MKS#319]
Have an option to pump out or in resources based on a right click setting on the module. 
Pump Out would would unload the module of resources as long as there is a place for them to go.
Pump In would collect resources from the vessel as long as there is any to be had.

**Comment by Tebryn** [comment]
You should probably should note that this is for the Proxy Logistics modules. (MKS ILM and others) and are you looking for a simple resource transfer from all containers on the vessel? or something to pull from the proxy logistics network? transferring from other containers on the same vessel are handled by stock fairly well TBH. 

I requested a proxy network 'Pump In' as part of a GUI option to disable proxy a while back, honestly it should have had a separate request though. thanks for submitting.

**Comment by Felson** [comment]
You are correct. that could have been more clear... Not sure how I forgot to mention that it was for Proxy Logistics. Reading my post now, I am not sure I would know what I meant in another week...

Pump Out would unload resources from the Proxy container INTO other containers on the same vessel provided there is room, and stockpile in itself if there isn't.
Pump In would draw resources into itself from other containers in the same vessel, provided it still has room, and the other containers aren't empty.

**Comment by enceos** [comment]
Looks like a Fuel Balancer feature, but on an automatic and offscreen passive mode.
