### ISSUE TITLE
Request For Solid Fuel

### ISSUE THREAD

**Issue by NihilRex** [UmbraSpaceIndustries/MKS#365]
Can you add Solid Fuel to the Fuel Refinery options, so we can turn LFO or LFO\Substrate into Solid Fuel for SRB builds?

**Comment by enceos** [comment]
I kinda wanted the feature myself. Had to create a procedural SRB and seps which use karbonite.

**Comment by errolkokbas** [comment]
Isn't there already provisions for making karbonite SRBs from karbonite?

**Comment by NihilRex** [comment]
Karbonite SRBs shake the ship to pieces...

And the largest problem with making a SolidFuel option for MKS is that SolidFuel is not pumpable.

**Comment by NihilRex** [comment]
Also I dont know how to github.

**Comment by theRagingIrishman** [comment]
you can't pump solid fuel soooooo
