### ISSUE TITLE
Akademy still not properly adding stars.

### ISSUE THREAD

**Issue by Nanderson423** [UmbraSpaceIndustries/MKS#376]
I tested out the new update and noticed that my Kerbals were still not gaining the proper number of stars, however, after looking at the source code for the akademy and my persistent file I think I found the issue. When checking to see if a crew already has the same logEntry.type and logEntry.target as the teacher, it is only checking the crews flight log, not their career log. This causes issues because in order to get off world to train (to minimus for example) the Kerbal trainee has to get in orbit of Kerbin, orbit of minimus, then land. All of which gets added to their flight log, causing their respective checks from the teacher to fail to add to the career log. Once again, to earn their stars they would have to return to Kerbin.

The two fixes I can see are to either just check their career log for the entry OR automatically move all flight data for each kerbal into their career log without the need for a teacher then copy anything left from the teacher to the student.

The second way would allow you to "promote" the first kerbal on or around planet (without a teacher) as long as they have an akademy in tow.

**Comment by richardhendricks** [comment]
I would like to see the Akademy do both functions, if possible:

1.  With no teacher present, any Kerbal who has flight log entries gets those entries converted to a career log with appropriate stars.  Removes the need to return to KSC for promotions above 3 stars.

2.  If a kerbal with more experience is present, he transfers his career log experience to noobs.
