### ISSUE TITLE
This goes WHERE?

### ISSUE THREAD

**Issue by Stikkychaos** [UmbraSpaceIndustries/MKS#395]
Hey, as mentioned on the forums, i would ask you to slap a "front" sticker on those logistics modules for the sake of sanity and comfort. I support thet would not take a lot of work, right?

**Comment by NoMrBond** [comment]
The Kerbal Foundries mod by Lo-Fi (http://forum.kerbalspaceprogram.com/threads/84102) includes orientation markers which are only visible in the VAB/SPH, could ask Lo-Fi about this feature?

**Comment by Stikkychaos** [comment]
Yes, I realise that, but that would also give some more immersion to the game - we are already striving to get self-sustainable bases as realistic as possible.
