### ISSUE TITLE
Non-inflatable extension parts!

### ISSUE THREAD

**Issue by janderssonGIT** [UmbraSpaceIndustries/MKS#397]
Cheers RD!

I noticed during my more ambitious project that the framerate suffers heavily with inflatable modules, such as the workspace module, agricultural, and the hab module. Obviously the design of these modules are around the compact 2.5m criteria.

But with the EPL extensions, these requirements doesn't have to constrain a player anymore. I wondering if you may consider implementing larger FTT sized hab, agricultural and workspace modules that are Not inflatable, but static objects without heavy animation!

The hab module could be a torus of the 5m size(or something along the lines of the 12000 torque SAS you added a while ago). The agricultural module could be a longer FTT octagon container with blast shutters that can be animated to let light in. Or just a static object like a tank, requiring an electricity feed for indoor UV lights for plant growth instead. And something similar for the workspace module aswell, the MKS workspace module works fine otherwise.

This would help ALOT for the more ambitous FTT projects, like these: https://www.youtube.com/watch?v=ODAdIYQGxBg (just for reference)

Thank you!

**Comment by BobPalmer** [comment]
Sure, those will mostly be solved with MkIV's, tho animation should not be the issue
