### ISSUE TITLE
Filter targets in logistics hub

### ISSUE THREAD

**Issue by koshboo** [UmbraSpaceIndustries/MKS#408]
first of all i love this mod my one main problem is that i use remotetech and when i go to do a transfer using the logistics hub all the satalites show up and i have top search though a list to find the vessels i want is it poissible to  add a filter to the list to show only 1 type of vessel.

**Comment by richardhendricks** [comment]
I accidentally found out that the Logistics Hub doesn't show asteroids - you could temporarily redesignate vessels you don't plan to ever transfer to as asteroids until this feature is in place.  Based on this line of code:

vessel.mainBody.name == ves.mainBody.name && ves.vesselType != VesselType.Debris && ves.vesselType != VesselType.SpaceObject && ves.vesselType != VesselType.Unknown

you could also designate vessels as Debris to remove them from the OL list, however Debris does get culled so I would stick with Asteroid.
