### ISSUE TITLE
Training Akademy CTD during re-entry

### ISSUE THREAD

**Issue by msholly** [UmbraSpaceIndustries/MKS#413]
I'm getting a twice reproduced crash to desktop when returning a simple rocket with the Training Akademy to Kerbin. Just a single KW rocket, a heat shield, and the Akademy really. 

Back when I was on Windows, there would be a nice crash log folder generated. Where would I find this on the Linux side? And what other information can I provide to assist with a potential bug fix?

Thanks!

**Comment by Joshwoo69** [comment]
I remember is player.log
found in the ksp_data
