### ISSUE TITLE
Adjustable module throughput

### ISSUE THREAD

**Issue by geoffromer** [UmbraSpaceIndustries/MKS#438]
From [the forum](http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-1%29-2015-05-02?p=1921822&viewfull=1#post1921822): "What about a slider to toggle the "throughput" of the refineries? If I could get it to use up less substrate / second, the same end result would be achieved."

I agree that this would be extremely handy.

**Comment by entropy-minus** [comment]
Ah, I was going to log this now but you were quicker :) I happen to have a few free days this week, so if you give me some pointers on where to start, I could try to implement the changes myself (my software development skills are probably around the bar of entry-level professional requirements).

Are you thinking about adding this to refineries, or to all MKS/OKS/UKS modules that do resource conversion?
