### ISSUE TITLE
Display module inputs and outputs

### ISSUE THREAD

**Issue by geoffromer** [UmbraSpaceIndustries/MKS#439]
It would be really nice if I could see what resources each module is consuming and producing, someplace like the Parts display. It would make it a lot easier to understand what my Kolony is doing. Right now the only source I've found for this information is the wiki, which isn't always up to date, and can't show the effect of things like productivity.

**Comment by BobPalmer** [comment]
Did you look at the station overview screen?

**Comment by geoffromer** [comment]
Is that the toolbar icon that looks like a satellite, next to the logistics manager? Yeah, I use that a lot (when I said the "Parts display" I meant the Parts tab of that window), but it doesn't have this information as far as I can tell (at least as of 0.22.9; I haven't gotten this far in 1.0 yet). I'm looking for per-module production and consumption, not the net for the whole base.
