### ISSUE TITLE
Multiple Error spam and unable to see vessel info tab

### ISSUE THREAD

**Issue by Prototype2001** [UmbraSpaceIndustries/MKS#449]
The first error spam is "[Error]: Actor::setLinearVelocity: Actor must be (non-kinematic) dynamic!" It goes away after the vessel loads between 10-20 seconds. http://i.imgur.com/U8wtL3s.jpg
Its tied to dampeners, having them disabled on the vessel removes this error and the vessel loads within 1-5 seconds as opposed to the previous stated load times.

Edit: Also this error appears when attempting time warp with at least 1 dampener engaged making time warp from the location impractical as the game lags to a fraction of what fps should be.

The second error spam appears when i try to hit this button http://i.imgur.com/puph4Yu.jpg 
This error prevents viewing information from the button shown in the picture, the more you hit the button the less transparent the window becomes, and the only way i can get rid of this window is re-loading the location of the vessel.

Edit: I'm able to get the second error in simple vessels, unlike the previous picture shows of several vessels connected together and upwards of several hundred parts. This vessel maybe has 20 parts to it and it occurs here as well http://imgur.com/uXOqex1. This error spam happens when the vessel overview button is pressed.

**Comment by BobPalmer** [comment]
Need to go through some of the station manager code as several part modules changed
