### ISSUE TITLE
Training Akademy

### ISSUE THREAD

**Issue by Prototype2001** [UmbraSpaceIndustries/MKS#451]
Scenario: 1 level 3 scientist   1 Level 0 scientist on kerbin VAB launchpad.
Training results in the level 0 becoming a level 3.

I don't think thats how its suppose to work.

**Comment by BobPalmer** [comment]
Probably due to that level 3 having a single really good flight.  It's an edge case that does happen from time to time - need to do some tweaks to the formula for training.

(Note to self:  Rather than limit by stars, limit by experience types when copying flight logs)
