### ISSUE TITLE
Texture missing.

### ISSUE THREAD

**Issue by elysoto** [UmbraSpaceIndustries/MKS#455]
[ERR 09:27:31.049] Texture 'UmbraSpaceIndustries/Kolonization/Assets/ModuleBase_NORM' not found!

**Comment by Neouni** [comment]
Might want to note that line above it:
[LOG 23:33:40.310] Load(Model): UmbraSpaceIndustries/Kolonization/Assets/MobileBase
[ERR 23:33:40.322] Texture 'UmbraSpaceIndustries/Kolonization/Assets/ModuleBase_NORM' not found!
