### ISSUE TITLE
Pioneer Module with mulch but no supplies stops working

### ISSUE THREAD

**Issue by HarlyKin** [UmbraSpaceIndustries/MKS#487]
The resource panel will show that mulch is being used (number is much higher than actual) but no supplies actually get created. 

Repo: Pioneer module with power, full mulch container, empty supply container and 1 kerbal.

**Comment by futrtrubl** [comment]
Are no supplies being created at all or are you just producing less than you consume?

**Comment by HarlyKin** [comment]
Hard to tell. The resource panel shows that mulch is being consumed at -8 or so but the resource itself hardly moves. The supply doesn't move and stays at zero. Could be that my kerbal just ate it as soon as it popped out of the oven. The oddity is that she has a little over 200% efficiency but only 20% utilization in the module so I figured the mulch should be going down faster. Even if she is creating more mulch almost as fast as she makes it then the resource number should be smaller (-8 used but +7 created)
