### ISSUE TITLE
Mk5 Sifter part triggering Ore collection mission too early

### ISSUE THREAD

**Issue by KraigL** [UmbraSpaceIndustries/MKS#517]
I think that early placement of the Mk-V Regolith Sifter part on tech tree has a side-effect of triggering the Ore collection missions to appear too early in a career game.  The Ore collection mission appear even though none of the Ore parts (scanning, harvesting or refining) are unlock on the tech tree yet.

**Comment by BobPalmer** [comment]
Stock issue unfortunately
