### ISSUE TITLE
Greenhouse can't operate on Kerbin with TAC-LS.

### ISSUE THREAD

**Issue by Corbald** [UmbraSpaceIndustries/MKS#550]
Since either TAC or MKS is allowing Kerbals to 'leave the window open' and use ambient air, no CO2 is generated, so the Greenhouse can't run. Kerbals in remote locations on Kerbal with this module will starve/dehydrate far sooner than expected, because NONE of the 'recyclers' run.

Suggest possibly separating food/water/oxygen recycling into different processes, which would also allow dedicated recycling of waste resource in large, specialized batches. e.g. recycling of just wasteWater for conversion into LFO.

**Comment by fmatosqg** [comment]
That solution can also fix another big issue with every single converter that produces the triplet food/O2/H2O: e.g. if you get full of water and short on food you'll eventually starve. 

Considering a casual case of having a base with a water drill or equivalent, when the converter tries to produce water it will find no available space and will stop, letting your food/oxygen levels falling indefinitely. This scenario also have the excess oxygen variation, and in theory there's another for running full of food.

Other scenarios are also problematic, one that pops in my head is about tiny imbalances on those long input/output ratios that can eventually pile up with long division, and in the long run you'll eventually get full of one resource and short on the other 2.
