### ISSUE TITLE
MKS Logistics Part

### ISSUE THREAD

**Issue by Mijna** [UmbraSpaceIndustries/MKS#556]
Can we get a small part that flags a vessel to be used in the MKS Logistics? This came up in the forum specifically for Drills that use Kontainers instead of ILMs so they can pull power.

**Comment by Lyneira** [comment]
I had a similar issue with an unmanned drill not getting power while being within 2 km of a staffed PDU. After spending several days trying to figure out why it wasn't working, I started digging through the code on github. Right now there are 2 possible conditions for logistics checks:
* Crew > 0
* Vessel has a part with ModuleResourceConverter

I would propose to add a third condition:
* Vessel has a part with ModuleResourceHarvester

This would make unmanned drills equipped with a MK-II ILM to both take power and share its resources when unfocused.

**Comment by LouisB3** [comment]
The workaround I'm using is to attach an empty MkV smelter to a spare node on my unmanned drilling vessels. The presence of a converter (even non-functional) means it's checked for logistics, so it will pull nearby power at the same time it shares output.
