### ISSUE TITLE
Provide cross-ship station overview

### ISSUE THREAD

**Issue by geoffromer** [UmbraSpaceIndustries/MKS#575]
In the new paradigm of having lots of disconnected modules connected by proxy/rover/PDU logistics rather than physical attachments, the resource levels and flows within a given module aren't very useful, because the module is just one slice of the whole system. Indeed, it can be nontrivial to even figure out things like how much longer the station can last on its current supplies, because the supplies may be getting rovered around while you're trying to count them (in my current base, levels of Supplies can jump up and down by hundreds of units every second or so, which is probably a bug, but even if they were more stable it would still be an issue).

It would be really handy if the station overview could cover the whole facility rather just than the current module. Obviously there are some subtleties about how you define "the whole facility", since two modules may be connected with respect to one resource but not another, but just combining all ships in physics range, and/or all ships in rover logistics range, would probably be good enough

**Comment by mhoram-kerbin** [comment]
Is #625 what you had in mind?

**Comment by geoffromer** [comment]
Yes, looks like just the thing.
