### ISSUE TITLE
Logistics Hub Error NAN

### ISSUE THREAD

**Issue by OakTree42** [UmbraSpaceIndustries/MKS#584]
Found a problem with logistics hub. Had this problem in the previous version but didn't isolate it. Right now I have it pretty isolated. Here is a nice little video clip of what happens. http://www.twitch.tv/oaktree42/v/8423102

Note I did move the craft to try if that would help, also went to that craft for focus. If you go to the whole stream you can find more of this at the end of it, but this highlight covers the core issue.

The log file says:
[EXC 12:48:34.102] ArgumentException: Getting control 3's position in a group with only 3 controls when doing mouseUp
Aborting
    UnityEngine.GUILayoutGroup.GetNext ()
    UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
    UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
    UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options)
    KolonyTools.MKSTransferCreateView.DrawWindowContents (Int32 windowId)
    KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
    UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
    UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[ERR 12:48:34.107] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)

I was able to initiate transfers to and from other vessels but NOT to or from the one in question here. No idea why, no F2-Errors at the other vessel site or really either site that was relevant until the transfer using the hub was attempted. Couldn't find a work around. Last time this happened it spread from the one vessel outwards as the game progressed so any ideas would be greatly appreciated.

**Comment by chrissnave** [comment]
I've had similar issues with certain vessels generating a NaN message when I attempt to move resources using EPL. For me it appears to have something to do with the Ship Manifest mod which I notice you're using. When I uninstalled Ship Manifest the problem went away. Perhaps a SM/EPL conflict?

**Comment by OakTree42** [comment]
Just tried the save game by removing the ship manifest mod, reloading and trying again. Error still persists in the same way. Log shows same issue. So at least this one does not seem to be ship manifest related from what I can tell.

**Comment by chrissnave** [comment]
Interesting. Okay will have to keep an eye on this issue. If its not SM then that may mean I can start using that again.

**Comment by OakTree42** [comment]
If it is SM then it is something it does to the save file and not having the mod active... but I don't think that's it here.... not from the F2 error file.

**Comment by chrissnave** [comment]
I just reinstalled SM & tried to reproduce the NaN error. Naturally now that I want it to act-up, its behaving its self... figures. I'll leave SM installed & report back if/when it occurs again (will snag some screen shots/F2 logs etc).

KSP 1.0.4
UKS 0.1.5
Ship Manifest 4.4.1.1

**Comment by chrissnave** [comment]
Okay the NaN monster has reared its ugly head once again. Here's my scenario...

Using Extraplanetary Launchpads & the USI orbital shipyard I manufactured a small ship in orbit. Before detaching I switched to my orbital logistics warehouse vessel & attempted to fuel the new ship by sending it some liquid fuel. Up popped the NaN error in the logistics window & a whole mess of red/orange spam in the F2 debug window...

![screenshot452](https://cloud.githubusercontent.com/assets/12790092/8886820/c31b07c2-323e-11e5-9c30-23c165baf8af.png)

So I shut down the session, re-stared KSP & proceeded to try to fuel it once again. This time I get just a few red/orange errors but no NaN message. The logistics fuel transfer works fine...

![screenshot453](https://cloud.githubusercontent.com/assets/12790092/8886848/186b49da-323f-11e5-8546-7d06d633168d.png)

So now I'm thinking Ship Manifest has nothing to do with this. I'd wrongly assumed that uninstalling SM had fixed the problem but it was more likely the session restart that did the trick.

I'm curious if you've using Extraplanetary Launchpads & if so was your buggy ship involved with any ship building?

KSP 1.0.4
UKS 0.1.5
EPL 5.2.0

**Comment by OakTree42** [comment]
In my case the logistics hub was built using EPL, But the ship causing the bugs was not, that was built and flown entirely from KSC. I'm going to go through the parts on the ship that's causing the 'bug' and see if there is a specific part that might be to blame... other than that for the moment I got nothing I can  suggest that might be making it only bug on one ship.

**Comment by OakTree42** [comment]
I've spent a few hours diving into this issue more deeply. And the errors we are seeing there in the F2 log has nothing to do with the NaN error, or rather I can recreate the F2 errors about the MouseUp without getting NaN, as it seems to have something to do with the formatting of the GUI calls for the interface but not specifically with the resources. I had thought it might be related to enriched uranium as I had that as a possible thought. As the one thing I could find in relation seemed to be various 'reactors' but that is not the cause either. I also looked at the math behind the location calculations, but again I couldn't see anything in the CS files or the save that would indicate that as the cause.

Still, I can say that the errors we are seeing in the F2 log are not related to the NaN issue directly as I can recreate those without any NaN errors. Also it seems to report differently if you use the left or right arrow to scroll through them.

**Comment by chrissnave** [comment]
Yeah that was my finding also. I got GUI MouseUp errors both with & without the NaN issue.

I have no clue if this is relevant but the esteemed Scott Manley was plagued by the "Not a Number" thing is this YouTube episode...

https://youtu.be/lrLaugFccPg

**Comment by OakTree42** [comment]
All the NaN error means is Not a Number - Which means some where in the code there is something that is trying to do math on something that isn't actually a number typically. For example if something had a value of two instead of 2. Or it can mean something was being divided by 0 sometimes. But it is a common code thing and so you'll see it all over if a program starts having issues. Once you get it, it can spread because once something starts showing as NaN rather than a number anything that tries to do math based on /that/ value will also turn into an NaN as it finds that 2 + NaN = NaN.

**Comment by OakTree42** [comment]
Confirmed that the missing radian issue is the problem with the NAN logistics hub, at least in my case. This is not related to the F2 series of errors which was a red-herring and a report from unity based on there likely being a spot where there is not an close end to one of the GUILayout calls in the interface for the Logistics hub. From what I can tell there probably is a missing GUILayout.EndHorizontal or GUILayout.EndVertical some where in there but I have yet to track it down for that part of the problem.

**Comment by chrissnave** [comment]
Although I'm not sure I understand this radian issue completely & not sure I need to, great to hear you've tracked down the problem. I've been getting the NaN issue with this one ship, maybe 1 in 10 sessions. Just enough to make me cringe every time I click the "Set" button. Looking forward to cringe-free play soon. Nice work.

**Comment by chrissnave** [comment]
Curious if any progress been made fixing this issue now that the problem has been isolated?

My Mun logistics hub was experiencing this NaN bug intermittently which I could live with but having just setup a colony on Duna my new "farm-base" is generating the NaN message 100% of the time (surface to surface transfer). As a workaround I'm using HyperEdit in place of the logistics hub when attempting transfers to/from my Duna farm but that's really messing with my sense of immersion, feels like I'm cheating.

If you need details I can supply them but this appears to be more of the same issue we discussed earlier in this thread.

**Comment by chrissnave** [comment]
I was excited to see a fix for the logistics hub NaN issue in yesterday's UKS 0.31.7 pre-release unfortunately after installing, the problem persists...

![logistics_hub_nan_issue_001](https://cloud.githubusercontent.com/assets/12790092/9971572/e1a5d9fc-5e2a-11e5-9b0d-317c16663532.jpg)

The hub works fine with all my other Duna vessels both in orbit & on the surface but not my farm. The logistics hub is on the surface, as is the farm if that helps.

KSP 1.0.4
UKS 0.31.7 pre-release

**Comment by frango9000** [comment]
KSP 1.0.5
UKS 0.33.8

EPL 5.2.95

On USI Station manager GUI clicking Parts Tab and Resources Tab I get errors
also all resources show "producing 0" but as expected some actually are being consumed and other generated. I also had ShipManifest, removed it and the problem persisted.

http://imgur.com/jIqXCjR

log:

> [EXC 11:38:03.007] ArgumentException: Getting control 0's position in a group with only 0 controls when doing mouseUp
Aborting
	UnityEngine.GUILayoutGroup.GetNext ()
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:38:07.969] Launcher here(in write): False
[EXC 11:38:09.520] ArgumentException: Getting control 1's position in a group with only 1 controls when doing mouseUp
Aborting
	UnityEngine.GUILayoutGroup.GetNext ()
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawResources (System.Collections.Generic.List`1 balance)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:38:16.532] [SCANsat] Height Map Of [Kerbin] Completed...
[LOG 11:38:16.656] [SCANsat] Loading Kopernicus On Demand PQSMod For the Mun
[LOG 11:38:18.004] Launcher here(in write): False
[LOG 11:38:28.024] Launcher here(in write): False
[LOG 11:38:38.041] Launcher here(in write): False
[LOG 11:38:41.357] ScienceAlert, Projected biome map in 51.38 seconds
[LOG 11:38:43.773] [SCANsat] Unloading Kopernicus On Demand PQSMod For the Mun
[LOG 11:38:43.773] [SCANsat] Height Map Of [the Mun] Completed...
[LOG 11:38:43.905] [SCANsat] Loading Kopernicus On Demand PQSMod For Minmus
[LOG 11:38:48.067] Launcher here(in write): False
[LOG 11:38:58.097] Launcher here(in write): False
[LOG 11:39:08.102] Launcher here(in write): False
[LOG 11:39:10.290] [SCANsat] Unloading Kopernicus On Demand PQSMod For Minmus
[LOG 11:39:10.290] [SCANsat] Height Map Of [Minmus] Completed...
[LOG 11:39:10.425] [SCANsat] Loading Kopernicus On Demand PQSMod For Gilly
[LOG 11:39:18.134] Launcher here(in write): False
[EXC 11:39:23.244] InvalidCastException: Cannot cast from source type to destination type.
	UnityEngine.GUILayout.BeginScrollView (Vector2 scrollPosition, Boolean alwaysShowHorizontal, Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUIStyle background, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginScrollView (Vector2 scrollPosition, Boolean alwaysShowHorizontal, Boolean alwaysShowVertical, UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[EXC 11:39:27.297] ArgumentException: Getting control 1's position in a group with only 1 controls when doing mouseUp
Aborting
	UnityEngine.GUILayoutGroup.GetNext ()
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawResources (System.Collections.Generic.List`1 balance)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:39:28.159] Launcher here(in write): False
[LOG 11:39:28.647] [CHATR] Capcom starts the exchange...
[EXC 11:39:34.692] InvalidCastException: Cannot cast from source type to destination type.
	UnityEngine.GUILayout.BeginScrollView (Vector2 scrollPosition, Boolean alwaysShowHorizontal, Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUIStyle background, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginScrollView (Vector2 scrollPosition, Boolean alwaysShowHorizontal, Boolean alwaysShowVertical, UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:39:35.853] [SCANsat] Unloading Kopernicus On Demand PQSMod For Gilly
[LOG 11:39:35.853] [SCANsat] Height Map Of [Gilly] Completed...
[LOG 11:39:35.980] [SCANsat] Loading Kopernicus On Demand PQSMod For Eve
[EXC 11:39:36.687] ArgumentException: Getting control 1's position in a group with only 1 controls when doing mouseUp
Aborting
	UnityEngine.GUILayoutGroup.GetNext ()
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawResources (System.Collections.Generic.List`1 balance)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:39:38.192] Launcher here(in write): False
[EXC 11:39:42.681] ArgumentException: GUILayout: Mismatched LayoutGroup.mouseUp
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type LayoutType)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginVertical (UnityEngine.GUILayoutOption[] options)
	KolonyTools.StationView.DrawResources (System.Collections.Generic.List`1 balance)
	KolonyTools.StationView.DrawWindowContents (Int32 windowId)
	KolonyTools.Window`1[T].PreDrawWindowContents (Int32 windowId)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 11:39:48.197] Launcher here(in write): False
