### ISSUE TITLE
Logistics Hub Problem

### ISSUE THREAD

**Issue by RealKolago** [UmbraSpaceIndustries/MKS#585]
I try to deliver resources from a craft (1) on the ground directly to at craft (2) in orbit with a logistics hub craft (3) in orbit. (all the same planet). Every time the Arrival is set to "0:NaN".

**Comment by RealKolago** [comment]
Strange, new craft (1) on the ground with logistics hub to at craft (2) in orbit gives me an Arrival "0:NaN" too.

**Comment by RealKolago** [comment]
Maybe a problem with my craft in orbit.

**Comment by OakTree42** [comment]
My case involves two craft on the ground but sounds the same. Interesting question, can you transfer to other things with the same hub? I found only one vessel seemed to be at issue here for the moment.

**Comment by RealKolago** [comment]
I can not transfer ground to ground. (Arrival: 0:NaN)
I can transfer space hub to ground.

**Comment by OakTree42** [comment]
I think we have two threads about the same issue that should/could be merged?

**Comment by chrissnave** [comment]
Agreed, I'm going to continue to discuss this in the issue #584 thread as that was created first.
