### ISSUE TITLE
Negative Costs for Parts

### ISSUE THREAD

**Issue by Lach01298** [UmbraSpaceIndustries/MKS#591]
This is the second time i'm posting for this bug.
If you empty all there resources of certain parts in the VAB then some parts have negative value reducing the cost this is a clear bug

examples are:
MKV agricultural module that has a cost of -1600
OKS Power Distribution Unit that with no enriched uranium cost -1000

**Comment by NoriSilverrage** [comment]
Do you have a full list?
I might take a stab at trying to fix it, but there isn't a quick way to find them all, so any that you find would be helpful.

**Comment by mhoram-kerbin** [comment]
Issue #598 is related to this and also shows some negative costs.
