### ISSUE TITLE
Strange costs for certain textures of Kontainers

### ISSUE THREAD

**Issue by mhoram-kerbin** [UmbraSpaceIndustries/MKS#598]
Using the 5m Kontainer with the texture NuclearFuels lowers the price of the container to about -7 million.

Using the organics texture with the Round Kontainer Tanks or the Kontainer Tanks rises the price to a multiple of that of the other textures - might be intentional.

**Comment by mhoram-kerbin** [comment]
Small addition:
The MK-V Supply Redi-Pak with the texture NuclearFuels also costs a negative amount of -400k.

**Comment by jd284** [comment]
Still present in 0.31.8 for the Redi-Pak (Nuclear Fuels is -481k cost) and 5m Kontainer (Nuclear Fuels is -7.8M cost).
