### ISSUE TITLE
Balancing the refinery-drill inbalance

### ISSUE THREAD

**Issue by mhoram-kerbin** [UmbraSpaceIndustries/MKS#631]
Currently the refinery is overpowered with respect to drills.

A refinery running at 25% (which is the absolute minimal efficiency it works at),
takes 0.625 units per second of Substrate, Minerals or MetallicOre as input.

A single drill that runs at a location with 10% resource concentration (which is the upper end) produces 0.1 units per second.

This means that more than 6 drills are necessary to let the refinery run at that capacity.

When we take a more realistic scenario with a refinery running at 100% and a resource concentration of 2% then 6.25 \* 4 \* 5 = 125 drills are necessary to support the throughput of the refinery.

I want to suggest to either reduce the throughput of refineries or increase the mining capabilities of drills so that it is possible to let the refinery run at full capacity with a reasonable number of drills.

**Comment by Gnurfos** [comment]
From my experience, this seem to lead to problems with substrate: excess polymers are dumped, while other logistic-connected vessels might need the substrate to produce organics (the link with this issue is that it is difficult to saturate the refinery in order to get some spare substrate).

**Comment by jd284** [comment]
@Gnurfos I like to tune my refinery by adding or removing machinery so that there's enough substrate left over for cultivation.
