### ISSUE TITLE
ILM balancing (OKS/UKS/MK-V)

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#642]
The variety of available ILM parts needs some balancing. The MK-V is underperforming (1/10th the capacity) while at the same time being the most expensive of them all for no apparent reason.

| Name / Part | UKS ILM / MKS_Storage_ILM | MK-V ILM / MKV_ILM | OKS ISM / OKS_Storage_ILM |
| --- | --- | --- | --- |
| Dry mass | 1.25 | 1.25 | 1.25 |
| Capacity factor | 1000 | **100** | 1000 |
| Cost | 1500 | **7500** | 1500 |
| Proxy logistics | **Yes** | No | No |

Furthermore the deflated capacity is the same for all three.

I suspect somehow the capacity and cost of the MK-V ILM and UKS ILM have been switched, or that proxy logistics should've been added to the MK-V ILM not UKS ILM. At least it'd make more sense that the proxy logistics function both costs more and eats available capacity. Rather than the opposite.

In any case it'd be a lot more sensible if the pure storage modules (MK-V ILM and OKS ISM) has the same stats, and the proxy logistics module (UKS ILM) were different.

Changing the capacity factor would not affect existing vessels, although to get the new capacity people would have to deflate the parts before upgrading.

**Comment by mhoram-kerbin** [comment]
MKV is not supposed to have Proxy Logistics. See also the link to RoverDudes post in #597.

**Comment by Goldenpsp** [comment]
Mhoram-kerbin.  I believe JD284 is just throwing out potential options for balancing the storage.  Personally I agree with the lack of proxy logistics on the MK-V but as it stands right now the numbers are out of whack.  I don't have an issue with the differences in storage capacity.  But the MKV should at least be lighter and less expensive than the UKS ILM. (or the USK ILM is heavier and more expensive).  Personally I think at 1500 the larger ILM's are a bit on the too cheap side.
