### ISSUE TITLE
Stop supplies being stolen from ships without converters.

### ISSUE THREAD

**Issue by magnevan** [UmbraSpaceIndustries/MKS#645]
Because of the pull logic of rover logistics in MKS, any ship within the colony that does not have a converter (thus does not pull supplies) will have all of it's supplies stolen. This makes it very difficult to:
1. Launch interplanetary ships from the colony, since it will have it's supplies stolen right away.
2. Build any crewed modules without MKS converters (rovers, drill modules etc)

Workaround right now is to have over 50% supplies in all other modules so that they don't steal, but this might be difficult in a budding colony

**Comment by magnevan** [comment]
Ideally supplies should be handled by a push logic I think. All the ships could be scanned for kerbals, and supplies would be redistributed so that total supplies in each vessel would be proportional to the number of kerbals in that vessel (barring space limits).

**Comment by chrissnave** [comment]
I agree although maybe Kerbals could be considered converters, as in they convert supplies to mulch? So any ship that has Kerbals on-board works with the existing pull logic.

Regarding the lack of control over where resources are taken from, I'd love to see some mechanism that allows/prevents the rover to see certain containers. Perhaps have a user controllable "logistics on/off" switch for each container? Or for even greater control & for dealing with competing converters give us the ability to assign containers & converters to "logistics loop A", "logistics loop B" etc.

**Comment by mhoram-kerbin** [comment]
@magnevan: 
As another workaround for your issue 1 you could temporarily remove the pilot from the rover until the interplanetary ship is launched.
Solving #188 for rover logistics would very likely help with this.

The new changes in 0.31.8 PRE allow to resolve your issue 2 by a ModuleManager-config patch (put a ModuleLogisticsConsumer into all manned pods):
[Changelog](http://forum.kerbalspaceprogram.com/threads/79588?p=2204646&viewfull=1#post2204646): "Separated logistics from MKS efficiency, so you can now easily have parts that are not MKS modules subscribe to rover logistics and power distribution. This module is added to all MKS modules and stock drills."

**Comment by BobPalmer** [comment]
Actually, they will not steal all supplies - there are lower bound rules.  Can you show me some examples of a specific colony where this is causing issues?

**Comment by jd284** [comment]
This is still an issue in 0.32, where we can't just take the pilot out of the rover to temporarily stop this behaviour.
