### ISSUE TITLE
[TAC-LS] Food-only converter for UKS Kerbitat (maybe OKS as well)

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#680]
On ground bases with availability of water from drilling, a TAC Water Splitter can be used to generate oxygen as well. Therefore only food would be needed from a habitat converter. Of course bases with no water supply would still require the standard food/water/oxygen conversion, so both should be available.

This also gets rid of the issue where one of the life support resources fills up and the converter stops running as a result, because each resource is produced by a different process:
Water: from drilling
Oxygen: from water splitter
Food: from Kerbitat

For OKS kerbitats this could be useful as well, though resources have to be shipped up anyway it would at least eliminate the issue of requiring venting parts here too. Also in combination with the TAC water purifier and CO2 recycler only food is needed to be supplied in the long term.

I added this with the MM patch added below, feel free to include it. I copied the USI definition and adjusted the food output rate to be mass neutral. The :Final is there to ensure the converter is added after the USI converters to make sure the module order is preserved; if you add it to the USI config that would no longer be necessary.

Another option that might make sense would be to generate oxygen and water directly from the Agroponics and Greenhouse converters (in addition to organics) and only generate Food from the Kerbitat in all cases, but that could break some savegames. However it would feel more biologically correct and would still uncouple the resource production to some degree. In this case it could be legitimate to dump excess water and oxygen production to fully uncouple them.

```
@PART[*_Kerbitat]:NEEDS[TACLifeSupport]:Final
{
    MODULE
    {
        name = ModuleResourceConverter
        tag = Habitat_Food
        ConverterName = Habitat (Food)
        StartActionName = Start Habitat (Food)
        StopActionName = Stop Habitat (Food)
        INPUT_RESOURCE
        {
            ResourceName = Organics
            Ratio = 0.0001
        }
        OUTPUT_RESOURCE
        {
            ResourceName = Food
            Ratio =   0.0001325115 

            DumpExcess = False
        }
        INPUT_RESOURCE
        {
            ResourceName = ElectricCharge
            Ratio = 6
        }
        INPUT_RESOURCE
        {
            ResourceName = Machinery
            Ratio = 0.000001
        }
        OUTPUT_RESOURCE
        {
            ResourceName = Recyclables
            Ratio = 0.000001
        }
        REQUIRED_RESOURCE
        {
            ResourceName = Machinery
            Ratio = 2000
        }
    }
}
```

**Comment by BobPalmer** [comment]
Not opposed to this really, bundle it up in the TAC-LS MM config I already include and do it as a pull request to develop with a summary of the change.
