### ISSUE TITLE
Add module information to the VAB/SPH tooltips

### ISSUE THREAD

**Issue by rocketmantis** [UmbraSpaceIndustries/MKS#687]
In particular, the MKSModule's workSpace / livingSpace numbers and its list of efficiencyParts with their multipliers would be great to have available ingame. 

The various logistics modules would also be nice to have show up in tooltips:
- ModuleLogisticsConsumer (just that it's present)
- ModuleResourceDistributor (same)
- ProxyLogistics (range, in m or km)
- ModulePowerDistributor (range)
- ModulePowerCoupler (range)
- Maybe also MKSLcentral, but that's so specialized that it's unclear what's worth putting in the tooltip. Maybe the list of ManagedResources.

I realize it's all documented in the wiki (and in the configs), but I found it difficult while learning the mod to keep track of all the different systems and what exactly they do. Having to bounce back and forth between KSP and a browser window, and then having to dig into the configs when it turns out that the docs are out of date... it's not the easiest. Having some of this info just pop up automatically when you're looking at a part in the VAB would be really convenient, and it might mean you don't need to spend as much time updating the documentation if/when you change numbers on things.

**Comment by chrissnave** [comment]
I was going to post something very similar to this, you've saved me the trouble. Yes it would be super handy to have this info available in the part's tool-tip.
