### ISSUE TITLE
Training Akademy

### ISSUE THREAD

**Issue by Prototype2001** [UmbraSpaceIndustries/MKS#709]
Orange suit kerbals (jeb, bill, val, & bob) work as intended according to the part description
White suit kerbals train everyone else up to their level, if I use a level 3 white suit on vab launchpad it trains everyone up to the trainer's level. Ex a level 3 pilot will train all pilots up to level 3 at the vab launch pad.

An issue with trained kerbals is that they cannot gain experience in any other means afterwards.
I have several trained level 1 scientists with their accomplishments of orbiting kerbin & landing on Mun(gained through training). Taking these level 1s on a trip to orbit Minmus and escape SOI of Kerbin should of leveled them to lvl 3 instead they obtained 0 experience from this trip due to training akademy.

**Comment by rtlagler** [comment]
Something I've noticed that may be related to this: although the text I get says that the Kerbals have been given 3 stars when I trained them with a max 3 star trainer, when I view them through the Kerbonaut Complex they appeared to have actually been given the proper number of stars (in my case, landed on Minus and trained by a 3 star dude, they were given 2 stars).
