### ISSUE TITLE
MK-V redi pak sized KIS storage

### ISSUE THREAD

**Issue by Goldenpsp** [UmbraSpaceIndustries/MKS#710]
for small base storage.

**Comment by jd284** [comment]
Isn't that what the saddle packs are for?

**Comment by Goldenpsp** [comment]
I don't think so.  This is a slightly larger storage that fits in between say a saddlebag and a Kontainer.

I would say the Saddlebag is roughly equivalent (in size and shape etc) to a Life support minipak, while a MK-V redi pack is well equivalent to a MK-V redi pak of supplies.

**Comment by BobPalmer** [comment]
yep, easy enough to add this in with a new texture.
