### ISSUE TITLE
OKS Power Distribution Hub

### ISSUE THREAD

**Issue by OakTree42** [UmbraSpaceIndustries/MKS#714]
This is a part request for a OKS part power distribution hub for space stations.

**Comment by jd284** [comment]
Why? Just use one of the reactors, they've superseded the OKS PDU. On the off chance that you really need to transfer power to other nearby vessel without docking you can also just include the MKS PDU in your station, though it'll look a bit weird.

**Comment by OakTree42** [comment]
True, you could (and I have) used a plain reactor but there is something really nice about the looks of the OKS modules and the ability to reprocess the ore on station. Which is why I requested it to be honest. Also use the OKS modules for long distance transports and the ability to reprocess depleated fuel back into usable is very handy.
