### ISSUE TITLE
Pioneer doesn't appear to pull karbonite from nearby kontainers

### ISSUE THREAD

**Issue by jrobnett** [UmbraSpaceIndustries/MKS#738]
Pioneer module doesn't appear to pull karbonite.  Pioneer module (2000 range) with an empty karbonite redi-pak a karbonite converter and a fuel saddle pak  near a random module with a redi-pak holding 1000 karbonite the converter reports no karbonite:

Save file is at: http://www.filedropper.com/testoks
Image of test is http://i.imgur.com/8REol1X.png

**Comment by BobPalmer** [comment]
Will need to add the appropriate modules to Karbonite's parts
