### ISSUE TITLE
[Warning]: [ProtoCrewMember Warning]: Crewmember Elizy Kerman found assigned but no vessels reference him. Elizy Kerman set as missing.

### ISSUE THREAD

**Issue by cdp1337** [UmbraSpaceIndustries/MKS#767]
Hey, not sure if anyone else has hit this issue before, but I seem to be having an issue with kerbals going missing as soon as I load a vessel nearby.
## Scenario:

I'm trying out MKS with a trial build-out beside the landing strip before I send everything out.  I have an UKS Aeroponics Module with 3x MK-V Agricultural Modules attached and 1x kerbal in each agriculture mod and 1x in the core module.  I also have a simple crane mover to position the modules into place as they have no propulsion otherwise.
## Reproduction:

I loaded the crane and move it off the runway.
I loaded the aeroponics module, switch to the crane ('[ ]' keys), move it to the aeroponics module, link (undocked) with KAS winch, move both off the runway, unlink modules.
I loaded a power module to repeat the same.
Immediately on loading the second module after the aeroponics has been moved off the runway, the kerbals on board mysteriously disappear. The only indicator in the log is 

```
[Warning]: [ProtoCrewMember Warning]: Crewmember Elizy Kerman found assigned but no vessels reference him. Elizy Kerman set as missing.
```

Any ideas?
## Environment:

Debian Stretch
KSP 64-bit
KIS, KAS, TACLS, USI and a few others.

**Comment by BobPalmer** [comment]
Please confirm you are on Linux 64 vs Windows 64.

**Comment by BobPalmer** [comment]
(nm just read you are on Debian).  I'll take a peek
