### ISSUE TITLE
Orbital Workshop issues

### ISSUE THREAD

**Issue by jd284** [UmbraSpaceIndustries/MKS#770]
The orbital workshop has a few issues (in addition to ticket #768):
- The texture is that of the pioneer module
- The mass (3t without machinery) is too high compared to the MKV workshop (0.75t), even accounting for being solid rather than inflatable it shouldn't be more than 1t, maybe 1.5t.
- The cost (55k) is also much higher than the MKV workshop (17.4k)
- It has a ReplacementParts resource but no life support recycler or hab module to make use of them

**Comment by BobPalmer** [comment]
Anything with crew has ReplacementParts.  Will look into the rest.
