### ISSUE TITLE
enriched Uranium goes poof!

### ISSUE THREAD

**Issue by OakTree42** [UmbraSpaceIndustries/MKS#809]
So after MUCH trouble shooting I think I've isolated the problem but have no idea how to fix it. I had built a small atomic powered rover, with an MKS reactor. I connected it to my base and transferred fuel into it (both reactors off, fuel was in, confirmed on stream). I then disconnect the new rover, and it has the fuel still...

One logistics tick later and POOF no more enriched uranium. I had two .625 and one 1.25 reactors, the .625 went from 2 to 0 and the 1.25 went from 22 to some where around 5 or 6ish. 

The fuel then appeared in the MKS Nuke Processor (confirmed with increase) and not even in the big reactor on the base. Now I thought it might be the rover logistics. (I had a karibou attached to the base by a KAS pipe).

So I moved the pilot out of the Karibou cockpit but it still happens. 

I repeated this several times. I tried it with even having the reactors on the rover running before I disconnected it and it still stole the fuel out of the reactors. 

I have no ILM for enriched uranium on my base so that is not the cause. So either it is somehow the rover or the MKS Nuke Processor itself. Looking at the cfg files my guess is the issue is with the:

ModuleResourceDistributor

Now I tried sorting through the source files to find that but to be honest ran out of time to find the location. Hopefully this is enough information to help pin down the bug.

I did look at the Output_log.txt file and could see the disconnect in the log, and the change of view in the log but nothing about the fuel transfer in the log. 

Also the rover started at 0 enriched uranium as it was built with EPL on site using stakes. So it was not reverting to an earlier state but was in fact syphoning the fuel away. 

I was able, once the rover was 2.4 km away from the base, to use the logistics hub to use the 'drone delivery' to send fuel to the rover, and that stayed.

**Comment by sh1pman** [comment]
Might be related to #801

**Comment by OakTree42** [comment]
Nope, in fact confirmed today that it was related to the rover logistics some how. Rover removed, no longer happens.
Plus it happened one 'tick' of logistics after disconnecting so wasn't part of any of the automated maintenence things I believe... so pretty much narrowed it down to rover logistics once the new craft is disconnected from the base. Had the same thing eat my water as a rover got into range of my base, stole all the life support water (all but 14 days of previously over a year) once I got into range.

So something with rover logistics is being rather greedy and perhaps it is related to the ILM being never full? Not sure on that part.
