### ISSUE TITLE
Life Support goes inactive after vessel reload

### ISSUE THREAD

**Issue by frango9000** [UmbraSpaceIndustries/MKS#810]
"Start Life Support" on all modules and they c̶o̶n̶s̶u̶m̶e̶ ̶m̶u̶l̶c̶h̶ ̶a̶n̶d̶ ̶f̶e̶r̶t̶i̶l̶i̶z̶e̶r̶ ̶t̶o̶ ̶p̶r̶o̶d̶u̶c̶e̶ ̶s̶u̶p̶p̶l̶i̶e̶s̶ (correction:  reduce supply consumption [jd284](https://github.com/jd284)), but this only occurs while im controlling the ship, if I go to a different ship Life Support stops and when i come back to the station all modules show "Life Support: inactive" but the action button displays "Stop Life Support", so i hit it once and it goes to "Start Life Support" and i hit it a second time to get it to start. 

Test Build:
OS: Ubuntu 15.10 64bit
KSP 1.0.5 (New install)

Mods:

UKS 0.33.8 (source: github release)
USI Tools 0.6.2 (included in UKS)
CRP 0.4.9 (included in UKS)
Firespitter plugin 7.1.5 (included in UKS)
USI-LS 0.3.12
MM 2.6.17 (included in UKS) & 2.6.18

Log
[KSP.log.txt](https://github.com/BobPalmer/MKS/files/139688/KSP.log.txt)
Save:
[persistent.sfs.txt](https://github.com/BobPalmer/MKS/files/139689/persistent.sfs.txt)
Craft:
[test.craft.txt](https://github.com/BobPalmer/MKS/files/139705/test.craft.txt)

**Comment by jd284** [comment]
Starting the Life Support functions shouldn't consume mulch, it should reduce supply consumption instead.

**Comment by frango9000** [comment]
Ok, My mistake on the mulch explanation detail, sorry about that, but i guess it is not normal for life support to go inactive after going to another ship and coming back the one mentioned, also ill add that any ship with any Life support that is left active will be inactive on vessel reload.

**Comment by liTeWave1** [comment]
I have this exact same issue. All life support is "inactive" after ship load.
