### ISSUE TITLE
Convert-O-Tron Request

### ISSUE THREAD

**Issue by OakTree42** [UmbraSpaceIndustries/MKS#816]
The ISRU convert-o-Tron 250 is simply not good enough for me right now.

I need something bigger and better. I miss the MK3 fuel processor. But I get not wanting that. Is there any way I could get an upsized convert-o-tron? Perhaps a 500? 1000? Also miss not getting engineer efficiency gains with the fuel processing? Just kinda a wish list thing.

**Comment by jd284** [comment]
You can just tweakscale it.

**Comment by OakTree42** [comment]
I don't use tweakscale. I have had too many issues with that mod.
