### ISSUE TITLE
Docking port not working in orbit

### ISSUE THREAD

**Issue by Odinzzz** [UmbraSpaceIndustries/MKS#844]
i have an issue with the docking port not working while im in orbit the work fine at KSC but im unable to assemble my station in space

**Comment by Xrave** [comment]
KSS and KSS1 attempting to rendevous in space (requires B9 Aerospace as well, and mechjeb) won't dock even when <0.4 meters away, no magnetic attraction.

[persistent.zip](https://github.com/BobPalmer/MKS/files/267022/persistent.zip)

Just to be sure, the 'door' texture of the docking port should face outwards right?

**Comment by Xrave** [comment]
Further testing also shows that two MKS docking ports do dock in KSC regardless of roll of docking port, and door texture ought to face outwards for docking behavior to happen.

**Comment by bendavieshe3** [comment]
Which MKS docking ports are these? I didn't think MKS shipped with any docking ports?

**Comment by Xrave** [comment]
OKS ports with the white donuts and lights.

**Comment by albebop** [comment]
I seem to be experiencing the same problem, but only on one port with a station that has two attached.  See Minmus Base 1 in this save.  I was able to dock my resupply probe to the OKS port near the bottom of the craft, but after decoupling and backing off (I went as far as >200m in trying to resolve this) I am unable to dock onto the open port on the other side of the base.  My intention here should be fairly obvious but I apologize if anything is unclear.


[persistent.zip](https://github.com/BobPalmer/MKS/files/382078/persistent.zip)

**Comment by rspeed** [comment]
I've had a lot of trouble getting construction ports to work in orbit, but in the end it came down to them being extremely picky about docking precision. Even with the torque and roll forces enabled – with all of the wobbling dampened out, they *still* won't dock 9 times out of 10. The common issue appears to be roll angle.

I can usually get it to dock dock instantly simply by changing the angle parameter – as soon as the slider changes everything snaps together. When that doesn't work, tapping one of the control key for rolling usually does the trick.

So I think this is probably a bug. Most likely the port roll force being slightly off from where it'll actually dock.

**Comment by RealKolago** [comment]
Yea, I have seen this problem with the construction ports too.

**Comment by dsbookbug** [comment]
I'm also having an issue where they refuse to connect, even after shoving them together with force, and trying every possible angle. They just refused to dock together.

**Comment by rspeed** [comment]
Has anyone else tried changing the angle slider?
