### ISSUE TITLE
The lightglobe generates an NRE for the dragcube.

### ISSUE THREAD

**Issue by smjjames** [UmbraSpaceIndustries/MKS#860]
Whether this was present in 1,0.5, I don't remember.

DragCubeSystem: Creating drag cubes for part 'MKS.LightGlobe'

(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

NullReferenceException: Object reference not set to an instance of an object
  at ModuleDeployableSolarPanel.AssumeDragCubePosition (System.String name) [0x00000] in <filename unknown>:0 

  at DragCubeSystem+<RenderDragCubes>c__IteratorC.MoveNext () [0x00000] in <filename unknown>:0 
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<RenderDragCubesCoroutine>c__IteratorB:MoveNext()
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<SetupDragCubeCoroutine>c__IteratorD:MoveNext()
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<CompileParts>c__Iterator4A:MoveNext()

**Comment by ibanix** [comment]
Same issue, under 1.1.0 with USI Core 0.2.1.0, UKS 0.40.1.1.

[LOG 22:09:17.237] PartLoader: Part 'UmbraSpaceIndustries/Kolonization/Parts/LightGlobe/MKS_LightGlobe' has no database record. Creating.
[LOG 22:09:17.251] DragCubeSystem: Creating drag cubes for part 'MKS.LightGlobe'
[EXC 22:09:17.255] NullReferenceException: Object reference not set to an instance of an object
    ModuleDeployableSolarPanel.AssumeDragCubePosition (System.String name)
    DragCubeSystem+<RenderDragCubes>c__IteratorC.MoveNext ()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    <RenderDragCubesCoroutine>c__IteratorB:MoveNext()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    <SetupDragCubeCoroutine>c__IteratorD:MoveNext()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    <CompileParts>c__Iterator4A:MoveNext()

**Comment by OakTree42** [comment]
Was going to report this but see it is well documented at this point. Still an issue in 1.1.2 with all the latest USI updates. Error occurs on game load, then not again that I can see. The rest of the info I had was basically the same as above.

**Comment by GarwelGarwel** [comment]
Surprisingly, still an issue.

**Comment by theRagingIrishman** [comment]
didn't see it in a clean install of MKS so closed
