### ISSUE TITLE
Extremly low framerates with bigger stations

### ISSUE THREAD

**Issue by taleteller** [UmbraSpaceIndustries/MKS#869]
Using KSP 1.0.5 i was having pretty bad framerates near stations. of course i blamed unity4 and waited KSP 1.1 to come up. Rates went up a lot since then, however not for MKS / OKS Stations. This is a screenshot of a vanilly only station containing 131 parts:

![vanilla_131parts](https://cloud.githubusercontent.com/assets/1484333/14935030/956407cc-0ec3-11e6-9ebd-ff571bb22e4c.jpg)

Framerate is decent nothing really to complain about. Load is 230% on my octacore, still potential for improvements. And here we got a OKS only station, not even doing anything but orbit, having only 51 parts: 

![usi_51parts](https://cloud.githubusercontent.com/assets/1484333/14935032/c726518e-0ec3-11e6-9c06-17542439573c.jpg)

Just using 180% cpu power. Same goes for MKS ground bases. Lacking multicore implementation?

My specs are:
- KSP 1.1.1 Linux x64
- AMD FX-8320 Octacore 3.5GHz / 16 GB / SSD 
- Gforce GTX 650Ti @ 1920x1200 (reducing rendering changes nothing at all)

**Comment by WazWaz** [comment]
Similar results with relatively small ground-based stations. Doesn't appear to be GPU related (turning graphics settings up or down has no effect).

**Comment by WazWaz** [comment]
Disabling all USI DLLs (but keeping the neutered parts) makes no FPS difference, so it's a bit odd.

**Comment by taleteller** [comment]
Doing some testing, i disabled all mods with the exception of joint reinforcements because without it everything goes kraken. Then i forked my a kerbitate to play around with. I even disabled the textures, modules, even replaced the model with a stock tank one. Still got 8.3 fps. Doing the same with stock hitchhiker containers gives me ~50fps. Framedrop with kerbitate starts in the VAB already.

Maybe a maintainer can have a closer look into that issue, for now i start to blame Squad.

**Comment by BobPalmer** [comment]
Attach the config file you were using.  If you moved/replaced any models or deleted any files, note that to so I can repro your exact case.

**Comment by taleteller** [comment]
I can give you my settings.cfg

[settings.cfg.zip](https://github.com/BobPalmer/MKS/files/246753/settings.cfg.zip)
[Physics.cfg.zip](https://github.com/BobPalmer/MKS/files/246772/Physics.cfg.zip)


Everything within Umbra, Firespitter, CommunityRessources or USITools is as provided in your downloads. Since none of the replacements or removals had a effect i undid them all together. 

List of Versions:

USI Tools - 0.7.2
Community Resource Pack - 0.5.1
Firespitter - 7.2.2
Interstellar Fuel Switch - 1.25
USI Core - 0.2.2
Freight Transport Tech - 0.5.1
Karbonite - 0.7.2
Kolonization Core - 0.2.2
USI-LS - 0.4.2
UKS - 0.40.1.1

Like WazWaz said, not even moving the dlls out of the way had an effect. Nothing in the log file contained any clue why the frames drop so massive. I can also give you some testingcrafts, however, beware they are called kraken for a reason! When i run 1.1.1 without Joint Reinforcements they start to dance when physic kick in:

[Krakencrafts.zip](https://github.com/BobPalmer/MKS/files/246768/Krakencrafts.zip)

Kraken2 is using kerbitats and gives me 8.3fps @ physics delta time 0.12
Kraken3 is using hitchhikers instead, giving ~40fps @ physics delta time 0.12

**Comment by BobPalmer** [comment]
What I mean is that you said you modified the Kerbitat config, removed the model and texture and all settings - which means by rights it was a completely different model and should have had no issue.  If it did, that's the config I would like to see.

Thanks!

**Comment by taleteller** [comment]
I see, now that would be this one:
[OKS_NoKerbitat.cfg.zip](https://github.com/BobPalmer/MKS/files/246800/OKS_NoKerbitat.cfg.zip)

I replaced model and attachment nodes by a stock tank. Also renamed author and manufacturer to prevent any broad mm patch for selecting it.

**Comment by taleteller** [comment]
For the means of completion, other mods are not affected. KIS Containers:
![screenshot106](https://cloud.githubusercontent.com/assets/1484333/14988828/e1d50928-1155-11e6-8cb7-3ba601909b9d.jpg)

Orbital Science Labs with excessive strutting to keep the kraken at bay:
![screenshot107](https://cloud.githubusercontent.com/assets/1484333/14988827/e1d3718a-1155-11e6-85ea-8493e6d8f728.jpg)

**Comment by WazWaz** [comment]
That NoKerbitat.cfg still appears to have all modules enabled.

My results (all based on Kraken2 but with struts and landing legs so as to avoid KJR, vsync off, DLLs all left in place, KSP 1.1.2, UKS 0.40.2.1 via CKAN), using m4v's "Show FPS" mod as Alt-F12 Performance seemed to give false "25" for anything under 25 and used 1-2 milliseconds/frame itself:

1. 21fps - Standard OKS.Kerbitat (but no Kerbals)
2. 34fps - fuel tank model, all OKS.Kerbitat modules (i.e. taleteller's cfg)
3. 35fps - OKS.Kerbitat model, but no modules
4. 83fps - fuel tank model, no modules

Next I did a series of tests taking case 4 and adding modules to separate out the causes of the difference between case 4 and case 2. The only config that showed significant changes was running with and without the ModuleCommand module - it accounts for nearly all of the difference.

This explains why the Hitchhiker can and science labs don't have this problem. The rest is that the Kerbitat model is obviously more complex than the fuel tank.

**Comment by WazWaz** [comment]
There are other performance problems I'm going to keep looking into, but I think this one boils down to "Parts, especially Kerbitat, possibly shouldn't use ModuleCommand".

**Comment by taleteller** [comment]
Indeed ModuleCommand seem to do a difference, is there anything special about this module and MKS or is is squad to blame?  I did some more testing myself:

Core testing element: 25 empty X32 tanks, 25 struts, 5 6way crossings, 2 stabilizers

- core alone: 36 fps in assembly / 60 fps on launchpad
- with 60 vanilla Mk1-2 command pods: 28  in assembly / 22 fps on launchpad
- with 60 Hitchhikers: 40  in assembly / 30 fps on launchpad
- with 60 OKS Station Tubes: 23 in assembly / 21 on launchpad
- with 60 OKS Storage: 27 in assembly / 25 on launchpad
- with 60 Kerbitats: 11 in assembly / 8.3 on launchpad

Testing with orbital segments mix (pioneer, agro, kerbitat, workshop). ground base segments are giving equal rates. 

12 pcs: 30 in assembly / 28 on launchpad
24 psc: 26 in assembly / 10.5 on launchpad
48 psc: 17 in assembly / 8.3 on launchpad
60psc : 8.3 in assembly / 8.3 on launchpad

Anything above a dozen working parts breaks down the frame rate for me. For example this real game science station around Mun:

![screenshot110](https://cloud.githubusercontent.com/assets/1484333/15007832/1a56141e-11dc-11e6-9c94-12fef82a7e2b.jpg)

Its not much of a size or part count, pretty much a joke compared to the artificial vanilla station I posted initially. My Minmus shipyard is way bigger and can only be docked in "slow motion" physics delta setting.

**Comment by Xrave** [comment]
Here's a theory. Maybe ModuleCommand is designed to have minimum crew = 1. I'm no expert in modding, but it seems like all Squad default parts have ModuleCommand with Minimum Crew 1, but the Kerbitats have minimum crew 0.

Minimum crew seems to be the # crew needed before it starts being a command module, but setting it to 0 means that it's essentially a probecore as well. So maybe if we add the Probe Core functionality separately it'll fix the lag issue?

**Comment by KevinMilcz** [comment]
The stock probe cores are made with minimumCrew = 0. I can confirm that removing the ModuleCommand from the kerbitat fixes lag. Basic ship with 64 kerbitats gets about 40 fps for me, removing the module from the cfg brings it up to my cap of 60. Surprisingly, adding an additional 64 probe cores on top of the same ship only drops the FPS to 45... Also tested with 64 Cupolas - Empty I sit at cap FPS, with 64 kerbals in them it drops down to like 30.

A quick search of the USI tools and USI Life support code didn't show any refs to ModuleCommand, so it's probably something up with stock.

[Kerbitat wtf.zip](https://github.com/BobPalmer/MKS/files/345360/Kerbitat.wtf.zip)
