### ISSUE TITLE
Flowcharts

### ISSUE THREAD

**Issue by mberthold** [UmbraSpaceIndustries/MKS#886]
Hi,
I ("bertibott") have created the first few ressource flowcharts (4 so far).
They are currently stored in this dropboxfolder: [https://www.dropbox.com/sh/y3ajih4wb4mt6ag/AACeGwGSDpgH1QK-iFHAHF3Ua?dl=0](url)

I have also opend a new gitHub Repo: [https://github.com/mberthold/Flowcharts](url)
Which is probably the better way to go.

As the source for my information I am using the UKS Math document: [https://docs.google.com/spreadsheets/d/1CBh6OPvjKjI6SW3rmLt14mUWgv9FEbdCsMQ7PTXK7XU/edit?pref=2&pli=1#gid=0](url)

Philosophy wise my approach would be to first creat charts focused around modules i.e. create charts that show what a given module can do (converting inputs into outputs.. Supplies -> Kerbal -> Mulch) as opposed to focussing around ressources and what we can do with them.

When I am done with that I would make a "big" chart like the one Iodestar posted in the thread.

**Comment by bendavieshe3** [comment]
Hi @mberthold - what are you suggesting is done with these?

**Comment by mberthold** [comment]
whatever you like really.
originally i spoke with sirreality (his alias in the forum not sure if it's the same here) about making charts for the wiki but if you have another use for them feel free to do so.

**Comment by mberthold** [comment]
update:
i have finished the charts for the idividual modules.

**Comment by BobPalmer** [comment]
Thank you :)  Tagging this as Docs/Help Wanted for Wiki integration
