### ISSUE TITLE
Training Akademy not allowing EVA

### ISSUE THREAD

**Issue by rtlagler** [UmbraSpaceIndustries/MKS#895]
I've put a bunch of Kerbals into a Training Akademy on Minmus and found that their portraits do not appear on the screen once they're inside.  I was able to use KIS to stick a Mk-V hab module onto the side and found that I could use the Transfer Crew functionality to move them from the Akademy to the hab, once they were in the hab their portraits showed normally and I was able to EVA them.  I am unsure if I've just missed something in the intended use of the Akademy or if this is a bug, apologies if it's expected behavior.

I'm using 1.1.2 and what I believe to be the latest versions of the mods.

**Comment by alexeybaj** [comment]
@rtlagler this patch has fixed it for me.
```
@PART[MK3_Akademy]:FOR[MyOverrides]
{

	INTERNAL
	{
		name = crewCabinInternals
	}

}
```

**Comment by rtlagler** [comment]
@alexeybaj Thanks much, it seems that I'll have you to thank for sending me down the rabbit hole in terms of modding parts.  I've applied a fix based on your solution and gotten this functionality working.

**Comment by rtlagler** [comment]
As an update to this for others coming across it in game: I've found that adding crewCabinInternals only allowed me to view four of the Kerbals in the Akademy, the remainder were not visible.

**Comment by IronCretin** [comment]
Click on the hatch of the part. That'll give you a list of kerbals for EVA or transfer.
