### ISSUE TITLE
UKS Drills don't produce heat

### ISSUE THREAD

**Issue by Businfu** [UmbraSpaceIndustries/MKS#896]
This is mainly a consistency issue: stock ore drill produces waste heat, none of the USI ones do.  Should be a straightforward fix.

**Comment by kjnicoletti** [comment]
I am working on a PR for this.

**Comment by kjnicoletti** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/72032-11-usi-kolonization-systems-mksoks-0400-planetary-logistics-and-kolony-rewards/&page=687#comment-2635740
