### ISSUE TITLE
Suggestion: Just add KSP-AVC as a dependency on CKAN

### ISSUE THREAD

**Issue by mcortez** [UmbraSpaceIndustries/MKS#901]
Why not just go ahead and add KSP-AVC as a dependency on your CKAN configuration?  Since people who use CKAN that report problems always end up resolving them through only 4 ways:
1. They wait and eventually CKAN sorts itself out
2. They uninstall and reinstall repeatedly with CKAN until it works
3. They give up and go away
4. They end up using KSP-AVC anyway to fix things

And while dealing with #1-#3 they bug the forums with issues that could just as easily be solved with KSP-AVC.

**Comment by BobPalmer** [comment]
Because CKAN even screwed up the KSP-AVC install ;)
