### ISSUE TITLE
error while starting up: loading stops at usi_reactor_125

### ISSUE THREAD

**Issue by DieGenie** [UmbraSpaceIndustries/MKS#904]
you named in USI-ReactorNFE.cfg the models usi_nuke_125, usi_nuke_250, etc, while in the folder the're called nuke_125, nuke_250 etc. you need to change one of those to make the mod work.
(sorry if bad english)

**Comment by Tsaven** [comment]
I don't think that's the cause of the problem.  Loading stopping at that part is due to a conflict with Near-Future-Tech reactors, they each have their own configs that conflict with each other.  If you read back a few pages in the UKS thread on the KSP Forums, you can find the details of what's required to fix this.

**Comment by mexoflex** [comment]
the problem is that when ksp starts, it uses the configuration file to search for the models. but if the names are different from those in the configuration file, then ksp can't find te models. rename the models by adding USI_ in the name. 
i did this and everything worked fine.

**Comment by dlejarazu** [comment]
Hi, I had the very same issue.
This is the log entry
`[LOG 10:25:31.332] PartLoader: Part 'UmbraSpaceIndustries/LifeSupport/Parts/Tank_375/LS_Tank_375' has no database record. Creating.
[LOG 10:25:31.340] DragCubeSystem: Creating drag cubes for part 'LS.Tank.375'
[LOG 10:25:31.374] PartLoader: Compiling Part 'UmbraSpaceIndustries/ReactorPack/Parts/USI_Nuke_125/USI_Nuke_125'
[ERR 10:25:31.413] Invalid boolean value! Field calculatedMass, value false; on object of type FNPlugin.FNGenerator

[LOG 10:25:31.438] PartLoader: Part 'UmbraSpaceIndustries/ReactorPack/Parts/USI_Nuke_125/USI_Nuke_125' has no database record. Creating.
[LOG 10:25:31.462] DragCubeSystem: Creating drag cubes for part 'USI.Nuke.125'
[EXC 10:25:31.508] NullReferenceException: Object reference not set to an instance of an object
	NearFutureElectrical.FissionReactor.GetInfo ()
	PartLoader.CompilePartInfo (.AvailablePart newPartInfo, .Part part)
	PartLoader+<CompileParts>c__Iterator4A.MoveNext ()`

Changing the names didn's solved it, unfortunately

Removing USI-ReactorNFE.cfg inside UmbraSpaceIndustries/ReactorPack solved it, though.

UKS v40.4.0
