### ISSUE TITLE
Logistics does nothing.

### ISSUE THREAD

**Issue by diffeq1** [UmbraSpaceIndustries/MKS#909]
Base 1 - Landed on Mun - Pioneer Lander, Kerbitat Lander, Supplies, Fertilizer, Nom-o-matic
Base 2 - Landed on Mun (36 m from Base1) - Command Pod, Empty supply.
Supplies on Base2 run dry, while Base 1 is maxed.
Adding Logistics hub made no difference.
Adding ILM made no difference.
All logistics windows are empty.

**Comment by cdp1337** [comment]
+1 on this.  I had two rovers just outside the runway, one with round kontainer tanks and one with a small round kontainer tank, drill, and ISRU.  They were meters away from each other and had plenty of electricity, but no auto fuel transfer even though both sets of tanks were marked as local and planetary warehouses.
