### ISSUE TITLE
Salamander Pod and ScoutLanderMk2 Base do not show up on Career tech tree.

### ISSUE THREAD

**Issue by Slightlylyons** [UmbraSpaceIndustries/MKS#919]
The Salamander parts are missing in career mode, I looked at the the config for the parts and they unlock on "simpleCommandModules" which isn't a node on the stock tech tree.

**Comment by mattpolicastro** [comment]
Bump. "simpleCommandModules" is a node on the [Community Tech Tree](https://github.com/ChrisAdderley/CommunityTechTree) add-on and shows up there, but not in stock.

**Comment by Slightlylyons** [comment]
That is what I figured, but the part should also be configured for the stock tech tree like every other part. Particularly because CTT is not updated too 1.2 yet and is also not a dependency.

**Comment by mattpolicastro** [comment]
Haha, yep. I was literally just starting to edit the .cfg files for the Salamander parts so they only use CTT when it's present. I guess they're available from the starting node?

**Comment by Slightlylyons** [comment]
I misread the previous comment to be a critique of my post, reread and realized it is simply a clarification. Not trying to start an argument. Thanks.

**Comment by mattpolicastro** [comment]
No worries. I'm forking so I can test then will (hopefully) submit a pull request soonish, as long as it's ok with @BobPalmer.

**Comment by Slightlylyons** [comment]
No idea. Balance wise I'd put it with the mk1 lander can.

**Comment by mattpolicastro** [comment]
Yeah, that or with the Landing parts?

**Comment by mattpolicastro** [comment]
Ok, I've got the changes added and they seem to be working OK: https://github.com/BobPalmer/MKS/commit/9ee68a76d7c579806791ea2c4cc7c6e712c3784e
