### ISSUE TITLE
Input resource typo in Tundra refinery

### ISSUE THREAD

**Issue by Dodecasaurus** [UmbraSpaceIndustries/MKS#924]
name = Tundra_Refinery
ConverterName = Chemicals 
INPUT_RESOURCE
ResourceName = Mineals

This is a typo and will prevent the Tundra refinery from turning minerals into chemicals. The typo is visible in the details of the module when rightclicked in the VAB.

**Comment by rtlagler** [comment]
I've created a PR with this update.

**Comment by cgruber** [comment]
This might be the same bug (or an equivalent bug) to #1202 which I just posted.  MPUs seem affected also.
