### ISSUE TITLE
Orbital Shipyard has broken lights, entire cupola glows solid white

### ISSUE THREAD

**Issue by stub42** [UmbraSpaceIndustries/MKS#964]
The orbital shipyard turns solid white and glows if you turn the lights on.

**Comment by cy-one** [comment]
I can support that. Although the texture seems to be broken as well. The octagonal "central" part is just white... and as stub42 said, glows bright white when the light is turned on.
![screenshot0](https://cloud.githubusercontent.com/assets/12306560/19572599/3632335a-9703-11e6-962d-2ee28613571c.png)
This also is true outside of the VAB

**Comment by jd284** [comment]
Still broken in 0.58.8

**Comment by davidpridemore** [comment]
I get the same issue as of today in 50.14
